### ISSUE TITLE
'--batch' not documented as necessary for non-interactive mode

### ISSUE THREAD

**Issue by badgerpants** [bucardo/bucardo#101]
The docs suggest that one can run 'bucardo install' non-interactively by simply specifying a value for  the --bucardorc option. Lies! You have to also specify '--batch', an option which is not described in the man page or (from what I could see) any of the other documentation.

**Comment by jifeon** [comment]
+1

bucardo is awesome, but documentation is often outdated and it's really hard to find some things like `--batch`. Which is only mentioned on [this page](https://bucardo.org/wiki/Bucardo/install) try to reach it from the main page..

**Comment by jonjensen** [comment]
@badgerpants @jifeon Thanks. `--batch` is now documented.
