### ISSUE TITLE
Can't add a sync

### ISSUE THREAD

**Issue by daisieh** [bucardo/bucardo#102]
Hi, I hope someone can help me! I've just set up bucardo 5.4.0 after deleting 4.4.8. I'm trying to sync Postgres databases and am running Postgresql 9.0. I dropped the old postgres bucardo schema and database and reinstalled bucardo from scratch.

I'm able to add dbs, tables, and herds, but when I try to add a sync, I get:

```
WARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=dryad_repo;host=datadryad.org;port=5432 at line 810.
CONTEXT:  PL/Perl function "validate_sync"
SQL statement "SELECT validate_sync('the_sync')"
PL/Perl function "validate_sync"
Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::st execute failed: ERROR:  null value in column "targetdb" violates not-null constraint at line 810. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at /usr/local/bin/bucardo line 4612.
```

The only hint I can find online (here: http://comments.gmane.org/gmane.comp.db.postgresql.bucardo.general/308) is that there shouldn't be a column "targetdb" anymore, but I dropped the bucardo schema and database and recreated them from scratch! I don't know what else I can do!

**Comment by jonjensen** [comment]
I'm not sure what was going on here, but this is over 5 years old and I haven't seen anything similar in recent years, so closing.
