### ISSUE TITLE
Customname has significant flaws

### ISSUE THREAD

**Issue by buukit** [bucardo/bucardo#104]
Hi,

Bucardo is amazing replication platform, but these is couple troubles / limits in configuration.

Our production environment contain dozens of Postgre databases. 
I will replicate them into Amazon Postgres RDS so that multiple source/master databases will go into the same slave database, but own schema. The idea works fine, but bucardo configuration is a bit tricky.

1st issue: Can't set customname so that it contains both params db and sync, if schema must be changed regarding of db and sync.
If add customname before sync it will say "sync not found". On other side, when trying add sync before customname, it can't find target tables.

This is mandatory for change schema on my case. Multiple schemas may contain same named tables and they should be routed into different schemas regarding db and sync.

I disabled constraints check on bucardo config db's customname table, insert customnames with db and sync params direct into table and enable again constraints check.
At last add syncs successfully and start bucardo. Works, but not so elegant procedure.

2nd issue: Customname don't work with sequences, I think.. This is significant flaw, when migrate production databases into a new environment and slave schemas has new names.
Only solution is alter sequence values manually before switch over.

At this time I have solved our needs using bucardo when keep mind the above flaws, but hopefully these will be resolved in future versions.
##

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
