### ISSUE TITLE
Failed configure MongoDB to Postgresql replication.

### ISSUE THREAD

**Issue by victordem** [bucardo/bucardo#106]
Hi.

Trying to configure MongoDB to Postgresql replication locally. Failed for now. 
Following PG to Mongo works for me:
http://blog.endpoint.com/2011/06/mongodb-replication-from-postgres-using.html

The questions are:
1. Does Mongo to Postgresql replication works in Bucardo?
2. It p.1 Yes, can you please point me to any sample configuration?

With best regards,
Victor.

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
