### ISSUE TITLE
Custom triggers not firing

### ISSUE THREAD

**Issue by andreas4all** [bucardo/bucardo#116]
Hi,

I have a master-master repllication on two postgresql servers. On both server I have a custom insert/update triggers. On first server where I make a change, there my triggers is firing (this is ok), but changes is replicated via COPY command to second server and there my triggers is not firing. Can you please help me?

**Comment by chall8908** [comment]
Bucardo sets "session_replication_role" to "replica" when copying data.  You will need to alter your trigger to fire always (or have a separate one that fires during replication).  The default settings will cause your trigger to not fire when the database is in "replica" mode.

You can accomplish this with the [ALTER TABLE](https://www.postgresql.org/docs/9.4/static/sql-altertable.html) command.
