### ISSUE TITLE
FATAL: password authentication when bucardo add tables

### ISSUE THREAD

**Issue by bodedra** [bucardo/bucardo#118]
**System specification:**

 - Ubuntu 14.04
 - bucardo version 4.99.10
 - psql (PostgreSQL) 9.3.14

**What I have tried so far?**

I have created master database with openerp postgres user.

    - Setup Source Database

        export SOURCE_HOST=localhost
        export SOURCE_PORT=5432  
        export SOURCE_DATABASE=master
        export SOURCE_USERNAME=openerp  
        export SOURCE_PASSWORD=openerp

    - Setup Destination Database
    
        export DEST_HOST=localhost 
        export DEST_PORT=5432  
        export DEST_DATABASE=slave  
        export DEST_USERNAME=openerp  
        export DEST_PASSWORD=openerp    
        
    - Finally, the tables to be migrated
    
        export TABLES="-t res_partner"
        
        export TABLES_WITH_SPACES="res_partner"
    
    - Set up the Destination Database
    
        cat >> $HOME/.pgpass <<EOL  
        $DEST_HOST:$DEST_PORT:$DEST_DATABASE:$DEST_USERNAME:$DEST_PASSWORD
        $SOURCE_HOST:$SOURCE_PORT:$SOURCE_DATABASE:$SOURCE_USERNAME:$SOURCE_PASSWORD
        EOL  
        
    - Create schema.sql 
    
    - Create Slave database
    
    - Load schema into Slave
    
    - Setting up Bucardo Sync (Source Database and  Destination Database) 
    
    - Now I am trying to add the tables we want to migrate and add them to a "copying herd"
    
        ./bucardo add tables res_partner db=master
        
I got following error:

>openerp@odedra-Lenovo-Z50-70:/usr/local/src/bucardo$ ./bucardo add tables res_partner db=master
DBI connect('dbname=master;host=localhost;port=5432','openerp',...) failed: FATAL:  password authentication failed for user "openerp"
FATAL:  password authentication failed for user "openerp" at ./bucardo line 8632.

I have analytic script bucardo. I have confusion with dbuser and dbpass variable declared at line number 84, 85.

    (I have tried with dbuser = 'openerp' and dbpass='openerp' but result same)

My *pg_hba.conf*

	# Database administrative login by Unix domain socket
	local   all             postgres                                ident

	# TYPE  DATABASE        USER            ADDRESS                 METHOD

	# "local" is for Unix domain socket connections only
	local   all             all                                     md5
	# IPv4 local connections:
	host    all             all             127.0.0.1/32            md5
	# IPv6 local connections:
	host    all             all             ::1/128                 md5
	# Allow replication connections from localhost, by a user with the
	# replication privilege.
	#local   replication     postgres                                peer
	#host    replication     postgres        127.0.0.1/32            md5
	#host    replication     postgres        ::1/128                 md5

List of database in my system:

                                       List of databases
        Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
    -------------+----------+----------+-------------+-------------+-----------------------
     bucardo     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     master      | openerp  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     slave       | openerp  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     slave_copy  | openerp  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     slave_copy1 | openerp  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     slave_copy2 | openerp  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
     template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
                 |          |          |             |             | postgres=CTc/postgres
     template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
                 |          |          |             |             | postgres=CTc/postgres

Afterwards, I have tried with add all tables and sequences using following commands.

    bucardo add all tables
    bucardo add all sequences

It's give me following error.

>Can't call method "prepare" on an undefined value at /usr/bin/bucardo line 6171.

How can I achieve master-slave functionality using Bucardo ?

**Comment by bodedra** [comment]
I have solved problem with updating _pg_hba.conf_ configuration file.

**Comment by hom7** [comment]
Hi，
    Updated the contents of pg_hda.conf?

> 我已经解决了更新_pg_hba.conf_配置文件的问题。
