### ISSUE TITLE
Feature Request: Selective Triggers

### ISSUE THREAD

**Issue by booleanbetrayal** [bucardo/bucardo#119]
We have a particular need (and if there's a potential workaround, I'm definitely all ears!) to support selective syncing of table operations. In our instance, we want to allow a particular events / auditing table grow indefinitely in our slave DB, but not necessarily in our master DB. The implementation idea is to allow for all other schema date to synchronize as usual, just not DELETEs on this specific table. This one table's growth rate is significant and introduces multiple management / downtime concerns on the underlying application (master DB).

Is this something Bucardo might be able to support? I know that Londiste (Skytools3) supports this functionality. We're still in the tool evaluation phase, but Bucardo seems much better managed / supported at this time. 

Thanks in advance for any insight / help!

**Comment by booleanbetrayal** [comment]
FWIW - londiste supports this through the `--tgflags` (trigger operation flags) switch. Might be a good convention.

**Comment by nbrustein** [comment]
+1

**Comment by jonjensen** [comment]
Patches welcome, I guess. Not actionable, so closing.
