### ISSUE TITLE
Validation failing for smallint between postgresql 9.2 and 9.5

### ISSUE THREAD

**Issue by olcrazypete** [bucardo/bucardo#120]
Using version 5.4.1 of Bucardo from posgresql yum repo on centos 7

I have a table with a column 'tempature' defined as a smallint in the schema as follows - 

   temperature smallint DEFAULT (-20),

9.2 and 9.5 seem to display this differently and I am getting a validation error and am unable to sync the table from 9.2 to a newly installed 9.5 server - both of which were installed using the same schema.  I am getting the following error - 

(19111) [Wed Sep 21 06:21:19 2016] MCP Warning: Source database for sync "syncAll" has column "temperature" of table "public.points" with a DEFAULT of "(-20)", but target database "tracks7" has a DEFAULT of "'-20'::integer"
(19111) [Wed Sep 21 06:21:19 2016] MCP Validation of sync syncAll FAILED

Is syncing between a 9.2 and a 9.5 server supported?  The purpose of bucardo for me in this instance it to upgrade the server to 9.5.

**Comment by rmadiwale** [comment]
Any update on this issue how to handle. I am also facing this issue with a DEFAULT of "(-1)".

**Comment by machack666** [comment]
I have a fix in a8f04b6.

**Comment by olcrazypete** [comment]
This did not seem to work for the issue I had in the original comment.

**Comment by kotsachin** [comment]
Hi Guys, 

It is said above that the above mention problem is solved but I am still facing same issue.
I am migration from PostgreSQL 9.3 to PostgreSQL 10.4.

Sync validation is failing with error is as below :
`107408) [Mon Jul 30 15:32:57 2018] MCP Inspecting target table "archive.ifta_fuel_file_record_p2017_06" on database "xrs_new9_target"
(107408) [Mon Jul 30 15:32:57 2018] MCP Inspecting source table "ods.segment_event_motion_state_change_p2018_07" on database "xrs_new9_source"
(107408) [Mon Jul 30 15:32:57 2018] MCP Inspecting target table "ods.segment_event_motion_state_change_p2018_07" on database "xrs_new9_target"
(107408) [Mon Jul 30 15:32:57 2018] MCP Inspecting source table "ods.segment_latest_vehicle_activity" on database "xrs_new9_source"
(107408) [Mon Jul 30 15:32:57 2018] MCP Inspecting target table "ods.segment_latest_vehicle_activity" on database "xrs_new9_target"
(107408) [Mon Jul 30 15:32:57 2018] MCP Warning: Source database for sync "sync_xrs_new9" has column "gps_latitude" of table "ods.segment_latest_vehicle_activity" with a DEFAULT of "(-100)", but target database "xrs_new9_target" has a DEFAULT of "'-100'::integer"
`
