### ISSUE TITLE
How to start a new sync?

### ISSUE THREAD

**Issue by hanks** [bucardo/bucardo#126]
version: build from latest master

I can not find a way to start a new sync task properly. Now I just restart bucardo itself.

For example, I add a new sync task, and the status now is like below,  how to start the new one `task1`

```
PID of Bucardo MCP: 30712
 Name                         State              Last good    Time    Last I/D    Last bad    Time
============================+==================+============+=======+===========+===========+===========
 task1                      | No records found |            |       |           |           |
 task2                      | Good             | 19:50:22   | 0s    | 0/0       | 09:44:16  | 10h 6m 7s
```

I tried `activate`, `kick`, but it does not work.

And one more question,  if I restart bucardo, will it lose some sync data?

**Comment by machack666** [comment]
Hi hanks,

I think you're looking for `bucardo start sync`, but there should be no harm in restarting Bucardo; it stores state in the database as far as rows needing to be sync'd and will pick up where it left off.

As long as the sync is active when Bucardo starts it should be handled as expected.

HTH,

David

**Comment by hanks** [comment]
@machack666 Thank you for your reply.

**Comment by hanks** [comment]
@machack666 I tried command below

```
> bucardo start task1
Checking for existing processes
Cannot start, PID file "/var/run/bucardo/bucardo.mcp.pid" exists
```

and it did not work

**Comment by RobertAtTegus** [comment]
Try `bucardo restart sync task1`
