### ISSUE TITLE
authentication failed for user "bucardo"

### ISSUE THREAD

**Issue by ghost** [bucardo/bucardo#127]
DBI connect('dbname=bucardo;host=localhost;port=5432','bucardo',...) failed: FATAL:  password authentication failed for user "bucardo"
FATAL:  password authentication failed for user "bucardo" at /usr/bin/bucardo line 308.

**Comment by efendimansur** [comment]
Have you permit bucardo user to access bucardo database in /usr/local/pgsql/data/pg_hba.conf using password?

I suggest you can permit bucardo user to access all local databases. Just add this config in last line of pg_hba.conf :
host    all         bucardo          	x.x.x.x/32      trust

x.x.x.x is your server ip address.

**Comment by pinkerltm** [comment]
> Have you permit bucardo user to access bucardo database in /usr/local/pgsql/data/pg_hba.conf using password?
> 
> I suggest you can permit bucardo user to access all local databases. Just add this config in last line of pg_hba.conf :
> host all bucardo x.x.x.x/32 trust
> 
> x.x.x.x is your server ip address.

Well wouldn't that allow anyone who connects to this server as username 'bucardo' from anywhere to login as superuser role without any further password check?

Having in mind to use bucardo in an production environment I would be interested where I can configure which password bucardo is using to connect to each cluster node.

**Comment by machack666** [comment]
You would want to set a password and use a`.pgpass` file to provide the password.
