### ISSUE TITLE
Feature request: Make reason_file's path configurable via command-line

### ISSUE THREAD

**Issue by machack666** [bucardo/bucardo#128]
From bucardo-general:

Hello

I have Bucardo running under postgres user. I am using init.d script to start/stop bucardo.

According to this:

if ('stop' eq $verb and $bcargs->{piddir}) {
   $STOPFILE = "$bcargs->{piddir}/fullstopbucardo";
   $REASONFILE = 'bucardo.restart.reason.txt';
   $REASONFILE_LOG = 'bucardo.restart.reason.log';
   stop();
}

Bucardo sets $REASONFILE to current dir if piddir is set. It doesn't set the reason_file dir option.

It tries to create bucardo.restart.reason.txt in current directory but It usually doesn't have permission to write to it. It also generates many thrash bucardo.restart.reason files.

Is it possible to add an option to specify reason_file as an argument for stop action (similar to pid-dir)? For example prepend $bcargs->{logdest} ?

Now the only solution is to remove pid-dir key from bucardo stop command in script but setting piddir in init.d scripts is common practise and is more convinient than in database.

Best regards, Andrey.

**Comment by kcappello** [comment]
Was running into this same problem and I finally got it working.   I changed the way that runuser was called in /etc/init.d/bucardo_11 by adding a -l to make it a login shell to start.

SU=runuser
changed to:
SU="runuser -l"
