### ISSUE TITLE
Unescaped backslash causes infinite loop

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#13]
In [this list thread](http://blog.gmane.org/gmane.comp.db.postgresql.bucardo.general/day=20120911), Gabriel Weinberg writes:

> We hit a problem query and bucardo kept trying it and got stuck in a loop. Is this because of some internal escaping bug?
> 
> KID Warning! Aborting due to exception for public.pages:? Error was DBD::Pg::db pg_result failed: ERROR:  syntax error at or near "R"\nLINE 1: ...Appeals of the Philippines','A','1'),('/\/\','','R','1'),('...\n                                                             ^ at /usr/local/lib/perl5/site_perl/5.10.1/Bucardo.pm line 8323.
> 
> Guessing it is the escaping of the backslash.

@turnstep asked for the version, which Gabriel replied with, 4.99.5.

**Comment by turnstep** [comment]
Closing for now, due to its age and inability to duplicate.
