### ISSUE TITLE
master - master setup single point of failure

### ISSUE THREAD

**Issue by oviwankenobi** [bucardo/bucardo#130]
in the master-master setup, if I understand correctly, bucardo is one point of failure, if the server the bucardo is installed on is going down there's no more replication and all the transactions while bucardo is down will be lost (not replicated); in the MySQL master-master if one server is down when it comes back up the replication starts where it is left of (in most cases). 
so, **can we set up Bucardo in same way as MySQL master-master works? each server replicates its changes to the other and they make sure whatever is replicated over is not replicated again back to itself?**
thank you.

**Comment by machack666** [comment]
Hi @oviwankenobi,

The individual changes to the database are queued up in so-called "delta" tables, so if the server where the Bucardo daemon is running goes down, the individual delta rows are still collected/maintained.  When the Bucardo daemon's service is restored these changes will be replayed.  (Of course, if the Bucardo daemon runs on the same server as one of the masters and is hosed, then it will lose any unreplicated changes in that server's delta rows.)

We do recommend you backup the "bucardo" database when changes have been made to the sync configurations so if that goes down you can restore information about the sync configurations, etc.

HTH,

David

**Comment by oviwankenobi** [comment]
ok, so I take it that bucardo master-master can not do what MySQL master-master setup can. 
thank you for your time David
