### ISSUE TITLE
RDS and Performance

### ISSUE THREAD

**Issue by betterrdms** [bucardo/bucardo#132]
I am new to Bucardo. I got two questions. Appreciate your assitance

Here are the questions - 1. Can I run it in large production environment of the database size of TB
Second question - Bucardo has its own database. Can I use AWS RDS even for Bucardo's own database..this is basically a client requirement to ensure they don't need to manage another databse

**Comment by saifulmuhajir** [comment]
I don't know about the performance since I am replicating small tables. But, yes you can use RDS as source and dedicated instance as a target (with plperlu available).

There's no difference in steps. Just install bucardo on the target DB and continue with everything as instructed.

**Comment by vivekanandg** [comment]
No you cannot use rds for the target db or bucardo's own db. This is because rds doesn't give you the full superuser access.

ref: https://serverfault.com/questions/661661/why-cant-i-create-a-superuser-in-aws-postgresql-instance

**Comment by analytically** [comment]
There's the `rds_session_replication_role` approach documented here: https://www.compose.com/articles/using-bucardo-5-3-to-migrate-a-live-postgresql-database/

**Comment by vivekanandg** [comment]
Thank you. This is nice.
