### ISSUE TITLE
DBI connect('dbname=bucardo;host=127.0.0.1;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at ./bucardo line 308.

### ISSUE THREAD

**Issue by vijaykrishnar** [bucardo/bucardo#133]
when i am trying to add source db to bucardo , i am getting 
 DBI connect('dbname=bucardo;host=127.0.0.1;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at ./bucardo line 308.

error.

Regards,
vijay

**Comment by dcvii** [comment]
similarly: trying `bucardo install`
DBI connect('dbname=bucardo;host=localhost;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at /usr/local/bin/bucardo line 9079.

**Comment by efendimansur** [comment]
@vijaykrishnar  

Have you permit bucardo user to access bucardo database in /usr/local/pgsql/data/pg_hba.conf using password?

I suggest you can permit bucardo user to access all local databases. Just add this config in last line of pg_hba.conf :
host all bucardo x.x.x.x/32 trust

x.x.x.x is your server ip address.

**Comment by efendimansur** [comment]
@dcvii 

I think you can try to add bucardo user and database in postgres : 

CREATE USER bucardo SUPERUSER; 
CREATE DATABASE bucardo OWNER bucardo;

Then you permit bucardo user to access all databases (pg_hba.conf).  Finally you can do command _bucardo install_ again.

Below are my configuration : 
Current connection settings:
1. Host:           localhost
2. Port:           5432
3. User:           bucardo
4. Database:       bucardo
5. PID directory:  /var/run/bucardo

**Comment by dwardu89** [comment]
@vijaykrishnar Try setting the value in the pg hba conf to md5
This method is probably overkill, but its worth trying. I had the same problem and it worked.

`
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 ident
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
host    replication     postgres        127.0.0.1/32             md5
host    replication     postgres        ::1/128                  md5`

**Comment by tbtommyb** [comment]
For anyone running into this problem, make sure that you add `host all bucardo 127.0.0.1 trust` (or similar) near the top of `pg_hba.conf`. If another matching rule is above it then it won't hit the new rule. Postgres logs should show which rule was selected if you run into problems.
