### ISSUE TITLE
Inconsistency in strict_check usage

### ISSUE THREAD

**Issue by olcrazypete** [bucardo/bucardo#135]
In man page and documentation the tag "strict_check" is used, but in practice the flag is "strict_checking"

This throws error
bucardo update sync SYNCNAME strict_check=false
Invalid setting: strict_check

This works
bucardo update sync SYNCNAME "strict_checking"=false

Man page describes the flag as follows
       "strict_check"
           Boolean indicating whether or not to be strict when comparing tables in the sync. If the columns have different names or data types, the validation will
           fail. But perhaps the columns are allowed to have different names or data types. If so, disable "strict_check" and column differences will result in warnings
           rather than failing the validation. Defaults to true.

**Comment by machack666** [comment]
Fixed in cd6fb9f.
