### ISSUE TITLE
Replicate Data from Postgres to Redis

### ISSUE THREAD

**Issue by sandyrandhawa** [bucardo/bucardo#136]
Hi,

Can anyone help to replicate data from postgres database to redis.

**Comment by machack666** [comment]
Hi @sandyrandhawa, Bucardo should support Redis as a target type; you would just need to specify the type in the `bucardo add db` line; e.g.:

```
bucardo add db A dbname=dbname
bucardo add db R dbname=dbname type=redis
bucardo add dbgroup pg1 A:source R:target
bucardo add sync some sync ... dbs=dbgroup
```

HTH.
