### ISSUE TITLE
BZ #124: bucardo crash on 'bucardo stop' 

### ISSUE THREAD

**Issue by machack666** [bucardo/bucardo#139]
Paul Theodoropoulos 2013-07-11 14:01:09 EDT
Created an attachment (id=19) [details]
Bucardo status, show, and relevant logs.

bucardo v5.0.0 from git repo.
debian v 6.0.7, 64 bit.
perl v5.10.1
postgresql v 8.4

I'm doing an initial buildout in a test environment. After setting up three
syncs, issuing a 'bucardo stop' sometimes results in the log output attached.
Also in the attachment is 'bucardo status all' output, and 'bucardo show all'.

I've no idea how serious this bug might be, or whether I'm just doing something
wrong.
[bucardo_status_log.txt](https://github.com/bucardo/bucardo/files/906973/bucardo_status_log.txt)

**Comment by jonjensen** [comment]
This is very old and we haven't had any recent reports of Bucardo crashing upon stop, so I'm closing this.
