### ISSUE TITLE
could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by HaiquanHe** [bucardo/bucardo#144]
When Bucardo stop sync for some reason(like connection stall) for a long time, after re-active sync , it will error:
2017-01-05 22:34:22 EST xxx xxx ERROR:  could not serialize access due to concurrent update
2017-01-05 22:34:22 EST xxx xxx STATEMENT:  /* Bucardo 5.3.1 */DELETE FROM public.xxxxxx WHERE device_id = ANY('{{"xxxxxxx

when delta have a lot of data, it will take a long time to sync , like 7mins, then because there are a lot of data in delta table, and the application may update one of these data at the sycn time,  so it fail and error.

If we have this issue, how we fix the issue to make the sync working again.

Is any way to make the sync task split to many little task? or other solutions?

**Comment by machack666** [comment]
Hi @HaiquanHe,

Have you tried this in the latest Bucardo release?  I note you're using 5.3.1, which is quite old at this point.

As far as your specific question, you can get support via the bucardo-general@bucardo.org mailing list. Please see this page for details:

https://mail.endcrypt.com/mailman/listinfo/bucardo-general

Best,

David

**Comment by oviwankenobi** [comment]
hi
I have exactly the same issue described by @HaiquanHe 
any chance anyone can give me some advice how to fix it?
the deltas are growing each minute and the sync between the two DBs is blocked

thank you very much
Ovi
