### ISSUE TITLE
Add new tables to existing sync then it is not syncing

### ISSUE THREAD

**Issue by chetankapoor** [bucardo/bucardo#147]
Hi 

I got some issue while I tried to add new tables in existing sync. But new tables was not syncing at all.
I did the following:
./bucardo add table public.test
./bucardo reload
Bit it doesn't work

 What are the steps to add new tables in existing sync..?

**Comment by machack666** [comment]
Hi, you can get support via the bucardo-general@bucardo.org mailing list.  Please see this page for details:

https://mail.endcrypt.com/mailman/listinfo/bucardo-general
