### ISSUE TITLE
Try build from git bucardo-logfiles.patch: Hunk #1 FAILED at 135, 161.

### ISSUE THREAD

**Issue by patsevanton** [bucardo/bucardo#148]
**git clone https://github.com/bucardo/bucardo.git**
Initialized empty Git repository in /home/centos/bucardo/.git/
remote: Counting objects: 9068, done.
remote: Total 9068 (delta 0), reused 0 (delta 0), pack-reused 9068
Receiving objects: 100% (9068/9068), 8.79 MiB | 4.34 MiB/s, done.
Resolving deltas: 100% (5857/5857), done.

**Create tar.gz from repo and copy bucardo-logfiles.patch**

**rpmbuild -ba Bucardo-5.4.1/dist/bucardo.spec** 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.BbaVuY
+ umask 022
+ cd /home/centos/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /home/centos/rpmbuild/BUILD
+ rm -rf Bucardo-5.4.1
+ /bin/tar -xf -
+ /usr/bin/gzip -dc /home/centos/rpmbuild/SOURCES/Bucardo-5.4.1.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd Bucardo-5.4.1
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (bucardo-logfiles.patch):'
Patch #0 (bucardo-logfiles.patch):
+ /usr/bin/patch -p0 --fuzz=0
+ /bin/cat /home/centos/rpmbuild/SOURCES/bucardo-logfiles.patch
**patching file bucardo.schema
Hunk #1 FAILED at 135.
Hunk #2 FAILED at 161.**
2 out of 2 hunks FAILED -- saving rejects to file bucardo.schema.rej
error: Bad exit status from /var/tmp/rpm-tmp.BbaVuY (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.BbaVuY (%prep)

**Comment by jonjensen** [comment]
Same as issue #73 which is now fixed.
