### ISSUE TITLE
Try build from git master-master-replication-example.txt': No such file or directory

### ISSUE THREAD

**Issue by patsevanton** [bucardo/bucardo#149]
After commented string with 'patch'
https://github.com/bucardo/bucardo/issues/148
#Patch0:  bucardo-logfiles.patch
#%patch0 -p0

**rpmbuild -ba Bucardo-5.4.1/dist/bucardo.spec** 
...................................
+ install -Dp -m 644 /home/centos/rpmbuild/SOURCES/master-master-replication-example.txt .
**install: cannot stat `/home/centos/rpmbuild/SOURCES/master-master-replication-example.txt': No such file or directory**
error: Bad exit status from /var/tmp/rpm-tmp.CWmS1f (%install)

**Comment by jonjensen** [comment]
@patsevanton Thanks for the report. This is fixed in commit https://github.com/bucardo/bucardo/commit/bfdb1f2820fc89675d905cce563eb64034314f19.
