### ISSUE TITLE
bucardo add sync failed

### ISSUE THREAD

**Issue by needf** [bucardo/bucardo#150]
bucardo add sync failed ,the log is
 "Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::db do failed: ERROR:  deadlock detected
DETAIL:  Process 33477 waits for AccessExclusiveLock on relation 6680077 of database 1270703; blocked by process 78287.
Process 78287 waits for AccessShareLock on relation 1270891 of database 1270703; blocked by process 33477.
HINT:  See server log for query details. at line 126. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at /usr/bin/bucardo line 4612.
"
in my postgres log it show add trigger operating and select operating deadlock. how can I avoid this.

**Comment by machack666** [comment]
Hi @needf; the approach to fixing it depends on if this is repeatable or not.

Can you post your question along with any relevant logs and the output of "bucardo list all" to the bucardo-general mailing list?  This is where we handle support requests.  (You can find list info here: https://mail.endcrypt.com/mailman/listinfo/bucardo-general)

Best,

David
