### ISSUE TITLE
Filtering while replication

### ISSUE THREAD

**Issue by vivekanandg** [bucardo/bucardo#152]
Is it possible to filter out some rows during bucardo replication?
I've looked at customcols, but it doesn't seem to serve this purpose.

I've read somewhere that setting custom triggers can solve this. Has anyone tried this approach?

**Comment by dojodominator** [comment]
I have not yet, but I am looking to do row level replication filtering

**Comment by sourvil** [comment]
Is this filtering ready?

**Comment by 858659744** [comment]
I'm trying Bucardo-5.4.1 the feature [CustomSelect](as said merged to CustomCols).
Couldnot add row filter on sync，but only columns.
Any one could give some suggestions?
---------------------------------------------------
I find the explaination here(https://bucardo.org/Bucardo/customselect/)

**Comment by bgold0** [comment]
Were you able to figure this out @858659744 @BryceDFisher @vivekanandg
