### ISSUE TITLE
validate_sync fails if replicating to new schema

### ISSUE THREAD

**Issue by einhverfr** [bucardo/bucardo#155]
Steps to reproduce:

1.  Create source and target databases.  Source has schema a, target has schema b
2. Add tables from source database, schema a
3. Add custom names moving database from schema a to schema b.
4.  Try to add sync

What happens:

validate_sync complains because schema a is not found on target db and throws an exception making sure you cannot add the sync.

This happens because the table is not replicated into the schema listed in goat but rather the customname.

I don't see a quick solution but I monkey-patched my production db to omit this check.

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
