### ISSUE TITLE
Recommendation:  set session_replication_role only if user is superuser

### ISSUE THREAD

**Issue by einhverfr** [bucardo/bucardo#156]
I use bucardo for a number of things.  It is a very capable, powerful database replication toolkit.  I use it for consolidation, reporting, and even migration of databases.  Recently I had to replicate some data from one db to another (partial set of tables), and I don't have superuser access to the other database.

I found in this case I had to disable setting the session_replication_role.

I would recommend that we have this variable set only if the db connection is a superuser connection.  The reasoning is that if you are replicating into a db you don't own, this variable is not your responsibility.

**Comment by einhverfr** [comment]
Actually as I think about it a better option would be to set this as a configuration on the sync.  We set it so that we can do things like multimaster replication but it prevents cascading replication.  If we make this configurable on the sync it means we can decide whether to allow cascading or multi-master on the destination dbs (i.e. whether to trigger further cascades on replication).

**Comment by einhverfr** [comment]
hmmm this could impact foreign key checks.  Need to think more.

**Comment by turnstep** [comment]
Not using session_replication_role would be a major change and I cannot truly see us implementing that without some serious safety checks. But I suppose it could be skipped if we are completely sure the target tables have no rules and no triggers, including system ones. Those checks would be more expensive than calling SRR itself, so the onus should probably be on the caller to supply a flag (or a sync/table attribute, as suggested above).
