### ISSUE TITLE
Deadlock when adding sync

### ISSUE THREAD

**Issue by deepakputhraya** [bucardo/bucardo#158]
When trying to create a sync.
```./bucardo add sync the_sync relgroup=copying_herd dbs=source_db:source,dest_db:target onetimecopy=2```

 I get the following error:
```
WARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=db;host=127.0.0.1;port=5432 at line 29.
Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::db do failed: ERROR:  deadlock detected
DETAIL:  Process 7282 waits for ShareRowExclusiveLock on relation 13603632 of database 16400; blocked by process 6606.
Process 6606 waits for RowExclusiveLock on relation 13603622 of database 16400; blocked by process 7282.
HINT:  See server log for query details. at line 126. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at ./bucardo line 4612.
```

I am trying to migrate from a self-hosted Postgresql to RDS.

**Comment by saifulmuhajir** [comment]
Adding sync will definitely require **exclusive lock**. I am sure this can be improved, but for the moment, you will need to make sure that no one is accessing the database during sync creation.

**Comment by jorgejimenez58** [comment]
check before is your postgresql isn't in recovery.
