### ISSUE TITLE
Switch between source and target?

### ISSUE THREAD

**Issue by saifulmuhajir** [bucardo/bucardo#159]
First of all, I thank you for this awesome project. It is really helpful for many of our cases.

We have setup source (S) and target (T) and it works fine. Now, how do I easily switch the hosts on the sync to be (S) is the new target and (T) is the new source? 

Do I do this by creating new sync and remove the old one, i.e: create new sync with (T) as source and (S) as target? Or is there any other way around?

Thanks

**Comment by jonjensen** [comment]
Will consider a docs example for this.
