### ISSUE TITLE
Error when trying to sync a database that is being synced with another database using bucardo

### ISSUE THREAD

**Issue by dwardu89** [bucardo/bucardo#162]
Hello,
I currently am working on a solution to use bucardo for database backup and restore.
Currently the setup is as follows:
There is 1 instance of `Bucardo 5.4.1` running on CentOS 7. It is pulling from a Source Database, and dumping on to the target database in real time.
That same instance of bucardo is then syncing the target database with another database to simulate a restore. However this problem happens every 8 seconds. And when i run `bucardo status` i get the following.

``` 
Name           State    Last good    Time      Last I/D    Last bad    Time
==============+========+============+=========+===========+===========+=======
 restore_sync | Bad    | 19:03:30   | 55m 7s  | 0/9       | 19:58:36  | 1s
 the_sync     | Good   | 19:32:21   | 26m 15s | 1/1       | none      |
```

ERROR in logs: 
`
(4032) [Wed Mar 14 19:55:18 2018] KID (restore_sync) Kid 4032 exiting at cleanup_kid. Sync "restore_sync" public.company Reason: DBD::Pg::st execute failed: ERROR:  query string argument of EXECUTE is null CONTEXT:  PL/pgSQL function bucardo.bucardo_delta_check(text,text) line 24 at EXECUTE at /usr/local/share/perl5/Bucardo.pm line 3400. Line: 5041 Main DB state: ? Error: none DB dest_db state: 22004 Error: 7 DB restore_db state: ? Error: none
`

I'm considering whether it's worth attempting to upgrade to `Bucardo 5.5.0` however there isnt a release marked in git which makes me think its not production ready.
Thanks

**Comment by jonjensen** [comment]
@dwardu89 It looks to me like most of the changes since Bucardo 5.4.1 were for testing and logging, so it should be pretty safe to upgrade.

@machack666 Do you have any concerns about running the latest from Git?

**Comment by dwardu89** [comment]
@jonjensen if that's the case, it might be best to create a release of Bucardo 5.5.0 if @machack666 is happy with the state. The problem is that there are two tests failing when i pulled 5.5.0.

**Comment by borball** [comment]
@dwardu89 Have you resolved the issue somehow?

**Comment by dwardu89** [comment]
@borball I ended up cleaning the bucardo database that was created in the source database. Then it clears it up.

**Comment by borball** [comment]
@dwardu89 Thanks, I found my issue was one special bucardo trigger (to kick replicaiton) was somehow deleted by mistake, it works now after I created it back.
