### ISSUE TITLE
Bucardo 5.5.0?

### ISSUE THREAD

**Issue by joshuabaird** [bucardo/bucardo#165]
Is there anything preventing a version bump to 5.5.0?  I see that `master` is at 5.5.0 and 5.4.1 was released back in 2016.

**Comment by machack666** [comment]
Hi @joshuabaird I'm actually in the process of preparing said release.  Working through a few of the open issues to see what other blockers there might be, then will roll it out fairly soon.

**Comment by joshuabaird** [comment]
Great - thanks.  Do you have any idea on a timeframe?  1 day. 1 week, 1 month?

**Comment by machack666** [comment]
I'd say closer to a week than the other two.  It really depends on tuits and which issues we want to close before.
