### ISSUE TITLE
FreeBSD rc script failed during boot time

### ISSUE THREAD

**Issue by Teetoow** [bucardo/bucardo#166]
Hi, 

The bucardo rc script is not working properly during boot time since FreeBSD forces the PATH environment variable which no more contains /usr/local/bin where perl is installed (check /usr/local/sbin/service for that purpose). Thus the "env perl" failed and bucardo cannot be executed.

A workaround is to add to /usr/local/etc/rc.d/bucardo:
PATH=$PATH:/usr/local/bin

And bucardo can be launched properly at boot time.

**Comment by jonjensen** [comment]
@Teetoow That's good to know. Would you like to submit a pull request that would update the docs or otherwise help FreeBSD users deal with this?

**Comment by jonjensen** [comment]
This was simple so I added it in commit 41bfd302f42f99a8. Closing.
