### ISSUE TITLE
Failure on "bucardo status <sync>"

### ISSUE THREAD

**Issue by crisistotal2014** [bucardo/bucardo#167]
Hi!
I'm using Bucardo v5.5.0 to replicate an AWS PostgreSQL to a OnPremise PostgreSQL and seems changes on tables are being replicated fine.
But when I've executed this command: bucardo status bookingbl
I've got this output:

> Last good                : May 23, 2018 12:34:14 (time to run: 1s)
> Rows deleted/inserted    : 0 / 0
> Last bad                 : May 22, 2018 07:47:11 (time until fail: 1s)
> Sync name                : bookingbl
> Current state            : Good
> Source relgroup/database : copying_herd_all / bookingbl
> Tables in sync           : 4
> Status                   : Active
> Check time               : None
> Overdue time             : 00:00:00
> Expired time             : 00:00:00
> Stayalive/Kidsalive      : Yes / Yes
> Rebuild index            : No
> Autokick                 : Yes
> Onetimecopy              : No
> Post-copy analyze        : Yes
> Last error:              : Failed : DBD::Pg::db do failed: ERROR:  permission denied to set parameter "session_replication_role" at /usr/local/share/perl5/Bucardo.pm line 5359. Line: 5037 Main DB state: ? Error: none DB dest_db state: 42501 Error: 7 DB source_db state: ? Error: none  (KID 4335)

log.bucardo shows all is running fine:

> (3264) [Wed May 23 12:34:14 2018] MCP Loading sync table. Rows=1
> (3264) [Wed May 23 12:34:14 2018] MCP Activating sync "bookingbl"
> (3264) [Wed May 23 12:34:14 2018] MCP Running validate_sync on "bookingbl"
> (3264) [Wed May 23 12:34:14 2018] MCP Connecting to database "dest_db" (target)
> (3264) [Wed May 23 12:34:14 2018] MCP DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=localhost
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" backend PID: 3266
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Local epoch: 1527078854.1702  DB epoch: 1527078854.17021
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Local time: Wed May 23 12:34:14 2018  DB time: 2018-05-23 12:34:14.170212+00
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Local timezone: UTC (+0000)  DB timezone: UTC
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Postgres version: 90513
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Database port: 5432
> (3264) [Wed May 23 12:34:14 2018] MCP Database "dest_db" Database host: localhost
> (3264) [Wed May 23 12:34:14 2018] MCP Connecting to database "source_db" (source)
> (3264) [Wed May 23 12:34:14 2018] MCP DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=...rds.amazonaws.com
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" backend PID: 31507
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Local epoch: 1527078854.20457  DB epoch: 1527078854.20274
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Local time: Wed May 23 12:34:14 2018  DB time: 2018-05-23 12:34:14.202737+00
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Local timezone: UTC (+0000)  DB timezone: UTC
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Postgres version: 90510
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Database port: 5432
> (3264) [Wed May 23 12:34:14 2018] MCP Database "source_db" Database host: ...rds.amazonaws.com
> (3264) [Wed May 23 12:34:14 2018] MCP Calling validate_sync on sync "bookingbl"
> (3264) [Wed May 23 12:34:14 2018] MCP   Inspecting source table "common-bookingbl-service.booking_files" on database "source_db"
> (3264) [Wed May 23 12:34:14 2018] MCP    Inspecting target table ""common-bookingbl-service".booking_files" on database "dest_db"
> (3264) [Wed May 23 12:34:14 2018] MCP   Inspecting source table "common-bookingbl-service.booking_sync_errors" on database "source_db"
> (3264) [Wed May 23 12:34:14 2018] MCP   Inspecting source table "common-bookingbl-service.schema_version" on database "source_db"
> (3264) [Wed May 23 12:34:14 2018] MCP    Inspecting target table ""common-bookingbl-service".schema_version" on database "dest_db"
> (3264) [Wed May 23 12:34:14 2018] MCP   Inspecting source table "common-bookingbl-service.sequence" on database "source_db"
> (3264) [Wed May 23 12:34:14 2018] MCP    Inspecting target table ""common-bookingbl-service".sequence" on database "dest_db"
> (3264) [Wed May 23 12:34:14 2018] MCP Active syncs: 1
> (3264) [Wed May 23 12:34:14 2018] MCP Entering main loop
> (3268) [Wed May 23 12:34:14 2018] VAC New VAC daemon. PID=3268
> (3268) [Wed May 23 12:34:14 2018] VAC DSN: dbi:Pg:dbname=bucardo;port=5432;host=127.0.0.1
> (3268) [Wed May 23 12:34:14 2018] VAC Bucardo database backend PID: 3269
> (3268) [Wed May 23 12:34:14 2018] VAC DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=...rds.amazonaws.com
> (3268) [Wed May 23 12:34:14 2018] VAC Connected to database "source_db" with backend PID of 31509
> (3268) [Wed May 23 12:34:14 2018] VAC Running bucardo_purge_delta on database "source_db"
> (3268) [Wed May 23 12:34:14 2018] VAC Purge on db "source_db" gave: Tables processed: 4
> (3264) [Wed May 23 12:34:14 2018] MCP Created VAC 3268
> (3264) [Wed May 23 12:34:14 2018] MCP Checking for existing controllers for sync "bookingbl"
> (3270) [Wed May 23 12:34:14 2018] CTL New controller for sync "bookingbl". Relgroup is "copying_herd_all", dbs is "bookingbl_2". PID=3270
> (3270) [Wed May 23 12:34:14 2018] CTL   stayalive: 1 checksecs: 0 kicked: 1
> (3270) [Wed May 23 12:34:14 2018] CTL   kidsalive: 1 onetimecopy: 0 lifetimesecs: 0 (NULL) maxkicks: 0
> (3270) [Wed May 23 12:34:14 2018] CTL DSN: dbi:Pg:dbname=bucardo;port=5432;host=127.0.0.1
> (3270) [Wed May 23 12:34:14 2018] CTL Bucardo database backend PID: 3271
> (3270) [Wed May 23 12:34:14 2018] CTL DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=localhost
> (3270) [Wed May 23 12:34:14 2018] CTL Database "dest_db" backend PID: 3272
> (3270) [Wed May 23 12:34:14 2018] CTL DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=...rds.amazonaws.com
> (3270) [Wed May 23 12:34:14 2018] CTL Database "source_db" backend PID: 31510
> (3270) [Wed May 23 12:34:14 2018] CTL Creating a new kid for sync bookingbl
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) New kid, sync "bookingbl" alive=1 Parent=3270 PID=3273 kicked=1
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) DSN: dbi:Pg:dbname=bucardo;port=5432;host=127.0.0.1
> (3264) [Wed May 23 12:34:14 2018] MCP Created controller 3270 for sync "bookingbl". Kick is 1
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Bucardo database backend PID: 3274
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=localhost
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Database "dest_db" backend PID: 3275
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) DSN: dbi:Pg:dbname=common-bookingbl-service;port=5432;host=...rds.amazonaws.com
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Database "source_db" backend PID: 31511
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Checking truncate_trigger table on database "source_db"
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Tables with deltas on source_db: 0 Without: 4
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Delta count for source_db."common-bookingbl-service".booking_files       : 0
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Delta count for source_db."common-bookingbl-service".booking_sync_errors : 0
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Delta count for source_db."common-bookingbl-service".schema_version      : 0
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Delta count for source_db."common-bookingbl-service".sequence            : 0
> (3273) [Wed May 23 12:34:14 2018] KID (bookingbl) Total delta count: 0
> (3270) [Wed May 23 12:34:14 2018] CTL Created new kid 3273 for sync "bookingbl"
> (3268) [Wed May 23 12:36:14 2018] VAC Running bucardo_purge_delta on database "source_db"
> (3268) [Wed May 23 12:36:14 2018] VAC Purge on db "source_db" gave: Tables processed: 4
> (3268) [Wed May 23 12:38:14 2018] VAC Running bucardo_purge_delta on database "source_db"
> (3268) [Wed May 23 12:38:14 2018] VAC Purge on db "source_db" gave: Tables processed: 4

"source_db" is an AWS database and "dest_db" is an OnPremise database.
Replication user is granted to use a SUPERUSER role and can execute this:
SET session_replication_role = replica;

Please, which can be the problem? It's dangerous?
Thanks!

**Comment by machack666** [comment]
Hi, you've tested `set session_replication_role=replica` on both databases and as the `bucardo` user (or whatever you're using as the replication user)?

**Comment by crisistotal2014** [comment]
Sure!
User I'm using for replication (not "bucardo") can do: set session_replication_role=replica;
on source and target PostgreSQL databases.


My current config (got with: bucardo show all) is:
> autosync_ddl              = newcol
> bucardo_initial_version   = 5.5.0
> bucardo_vac               = 1
> bucardo_version           = 5.5.0
> ctl_checkonkids_time      = 10
> ctl_createkid_time        = 0.5
> ctl_sleep                 = 0.2
> default_conflict_strategy = bucardo_latest
> default_email_from        = 
> default_email_host        = 
> default_email_port        = 25
> default_email_to          = 
> email_auth_pass           =
> email_auth_user           =
> email_debug_file          =
> endsync_sleep             = 1.0
> flatfile_dir              = .
> host_safety_check         =
> isolation_level           = repeatable read
> kid_deadlock_sleep        = 0.5
> kid_nodeltarows_sleep     = 0.5
> kid_pingtime              = 60
> kid_restart_sleep         = 1
> kid_serial_sleep          = 0.5
> kid_sleep                 = 0.5
> log_conflict_file         = bucardo_conflict.log
> log_level                 = verbose
> log_microsecond           = 0
> log_showlevel             = 0
> log_showline              = 0
> log_showpid               = 1
> log_showsyncname          = 1
> log_showtime              = 3
> mcp_dbproblem_sleep       = 15
> mcp_loop_sleep            = 0.2
> mcp_pingtime              = 60
> mcp_vactime               = 60
> piddir                    = /var/run/bucardo
> quick_delta_check         = 1
> reason_file               = bucardo.restart.reason.txt
> reload_config_timeout     = 30
> semaphore_table           = bucardo_status
> statement_chunk_size      = 6000
> stats_script_url          = http://www.bucardo.org/
> stopfile                  = fullstopbucardo
> syslog_facility           = log_local1
> tcp_keepalives_count      = 0
> tcp_keepalives_idle       = 0
> tcp_keepalives_interval   = 0
> vac_run                   = 30
> vac_sleep                 = 120
> warning_file              = bucardo.warning.log

How can I enable more verbose Bucardo commands?

**Comment by crisistotal2014** [comment]
Please, do you have any recommendation?

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
