### ISSUE TITLE
"bucardo remove all sequences" command fails on answering

### ISSUE THREAD

**Issue by crisistotal2014** [bucardo/bucardo#168]
Hi!
"bucardo remove all sequences" command fails on answering "y" (using "1" doesn't do anything).

Using this command:
bucardo remove all sequences
remove sequences but shown failures
> Are you sure you want to remove all sequences? y
> Argument "common-bookingbl-service.schema_version" isn't numeric in sort at /usr/local/bin/bucardo line 3729, <STDIN> line 1.
> Argument "common-bookingbl-service.booking_files" isn't numeric in sort at /usr/local/bin/bucardo line 3729, <STDIN> line 1.
> Argument "common-bookingbl-service.booking_sync_errors" isn't numeric in sort at /usr/local/bin/bucardo line 3729, <STDIN> line 1.
> Argument "common-bookingbl-service.sequence" isn't numeric in sort at /usr/local/bin/bucardo line 3729, <STDIN> line 1.
> Use of uninitialized value in string ne at /usr/local/bin/bucardo line 3731, <STDIN> line 1.
> Use of uninitialized value in string ne at /usr/local/bin/bucardo line 3731, <STDIN> line 1.
> Use of uninitialized value in string ne at /usr/local/bin/bucardo line 3731, <STDIN> line 1.
> Use of uninitialized value in string ne at /usr/local/bin/bucardo line 3731, <STDIN> line 1.
> Removed the following sequences:
>   common-bookingbl-service.booking_sync_errors_id_seq
>   common-bookingbl-service.sequence_sequence

Please, can be fixed this?

Thanks!

**Comment by crisistotal2014** [comment]
Please, do you have any recommendation?

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
