### ISSUE TITLE
bucardo message "<some text with!>" fails

### ISSUE THREAD

**Issue by crisistotal2014** [bucardo/bucardo#169]
Hi!
I've detected when I want to print a message (with an exclamation) on log file through:
bucardo message "<some text with!>" fails like this:
-bash: !": event not found
and no line is added on logfile.

This seems a fatal security error.

Please, can fix-it?
Thanks!

**Comment by machack666** [comment]
Hi @crisistotal2014,

This is coming from your shell, not Bucardo; you can see a similar effect via:

```shell-session
$ echo "foo!"
-bash: !": event not found
```

As such, you just need to escape in the normal way, via \! or single-quoted strings.

Best,

David

**Comment by crisistotal2014** [comment]
Sure!
In this case, can you change text entry on help from:
"message <body>"
to a more clean text, like:
"message '<body>'"

Thanks!

**Comment by jonjensen** [comment]
@crisistotal2014 Sure, we can do that. I just pushed out a change.

People still need to understand shell quoting context, since `message '...'` will go wrong if they have a `'` in their message body. But maybe the change will help someone.
