### ISSUE TITLE
Online documentation is quite broken

### ISSUE THREAD

**Issue by gramki** [bucardo/bucardo#173]
Many links like the below give 404:
https://bucardo.org/Bucardo/FAQ.md
https://bucardo.org/Bucardo/bucardo.md

Linked from main doc page:
https://bucardo.org/Bucardo/

**Comment by rlafferty** [comment]
Looks like the online documentation has recently been updated, and the links work correctly now (note the URIs have changed from what you have listed above).
* FAQ: https://bucardo.org/Bucardo/FAQ.html
* bucardo: https://bucardo.org/Bucardo/bucardo.html

I'd say it's probably safe to close this?

**Comment by machack666** [comment]
Thanks for checking in; yup, let's close it.  There are definitely a lot more things that could be improved about the docs, but we did an initial pass to try to correct any broken links.
