### ISSUE TITLE
Can we cut 5.4.2

### ISSUE THREAD

**Issue by luss** [bucardo/bucardo#176]
Seems to me there have enough usefull/stable things checked in over the last two years to tag & release.   I think it's important, at the very least, to demonstrate that this project is far from dead.   If y'all feel there isnt enough new functionality to call it 5.5.0, then please call it 5.4.2.

**Comment by machack666** [comment]
Hi @luss agreed on this.  We can roll 5.5.0 soon; I'll try to mop up some of the outstanding bugs/issues or at least triage and see if there is anything particularly egregious which would need to be fixed prior to a release.
