### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by gustavotonini** [bucardo/bucardo#177]
Hello,
We have a bucardo setup with 14 dbs and 91 syncs due to the requierement of continuing to replicate among other nodes when one of them goes down.

Bucardo is using 36GB of RAM and sometimes some syncs get stuck.

Is there a way to optimize this scenario?

**Comment by PrinLiu** [comment]
It should be the same issue as this one I think. https://github.com/bucardo/bucardo/issues/115
