### ISSUE TITLE
bucardo is not postgresql 11 compatible

### ISSUE THREAD

**Issue by dlucredativ** [bucardo/bucardo#178]
Bucardo relies on `pg_class.relhaspkey` which does not exist in pg11 any more.

**Comment by machack666** [comment]
Thanks, will look for a workaround.

**Comment by machack666** [comment]
Pushed what should be a backwards-compatible change in 2358ada.  Can you test/confirm this works for you?

**Comment by dlucredativ** [comment]
It seems to work, at least my check_postgres_replicate_row is fine now.
