### ISSUE TITLE
Could not serialize, will sleep for 0.5 seconds

### ISSUE THREAD

**Issue by mridude23** [bucardo/bucardo#180]
Hi,

As the title suggests I keep getting these kind of errors and it interrupts all the flow for that sync.
For example, I have about 80 tables in a sync, but for now only about 20 of them have data in delta tables waiting to be replicated. 
These tables will need to replicate in 4 different targets. 2 of them succeed, but 2 of them fail with `Could not serialize, will sleep for 0.5 seconds` which starts everything  from scratch again. It seems that at the same table it fails each time. 

Any ideas what to do here?

**Comment by mridude23** [comment]
Hi guys, 

Anyone with ideas? I seem to keep getting these, but for now no idea how to tackle them.

**Comment by machack666** [comment]
How much traffic is on this machine?

**Comment by mridude23** [comment]
> How much traffic is on this machine?

Referring to traffic/sec? When the issue arose, did not see more than 2-4 MB/s.
What's weird is that I have 3 more syncs that do the same thing and no issues there. Also all of these are in the same network, a gigabit one. so it should not be a network issue in my opinion.

**Comment by machack666** [comment]
What does `SHOW transaction_isolation` and `SHOW default_transaction_isolation` show on the nodes in question?

**Comment by mridude23** [comment]
Edit: Still having this issue, for the same server. Did not mention, Bucardo 5.4.1. From what I can gather, something happens and the sync somehow fails to do it's job. Checked the logs but can't find what it actually happens. For example:
- had a sync that failed because it was not available anymore in sync table (failing with violation when inserting in syncrun)
- some errors later, all syncs died
- kid's were recreated for all
- the sync with serialization issues, started to show serialization errors; this being the start, 8 hours later, a lot of data in the delta, failing with serialization error after a few tables

**Comment by mridude23** [comment]
This issue seems to be resolved on Bucardo 5.5.0. Although I'm having some other issues, this one will be closed. If it resurfaces, I will reopen it.
