### ISSUE TITLE
DBD::Pg::st execute failed: ERROR:  DBI connect('dbname=test1;host=127.0.0.1;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at line 63. CONTEXT:  PL/Perl function "validate_goat" at /usr/local/bin/bucardo line 7292

### ISSUE THREAD

**Issue by hom7** [bucardo/bucardo#185]
Server: ubuntu14.04 x86  bucardo: 5.5.0  postgresql: 9.5

I have some problems, I don’t understand the cause of the error very well.

##############
DBD::Pg::st execute failed: ERROR:  DBI connect('dbname=test1;host=127.0.0.1;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at line 63.
CONTEXT:  PL/Perl function "validate_goat" at /usr/local/bin/bucardo line 7292.
##############
-------------------------------------------------------------------------------------------------------------------
bucardo list dbs
Database: test1  Status: active  Conn: psql -p 5432 -U bucardo -d test1 -h 127.0.0.1

bucardo add all tables
DBD::Pg::st execute failed: ERROR:  DBI connect('dbname=test1;host=127.0.0.1;port=5432','bucardo',...) failed: fe_sendauth: no password supplied at line 63.
CONTEXT:  PL/Perl function "validate_goat" at /usr/local/bin/bucardo line 7292.

**Comment by buzzing-bee** [comment]
Try read on this issues below:
[https://github.com/bucardo/bucardo/issues/133](Issues 133)
[https://github.com/bucardo/bucardo/issues/140](Issues 140)
