### ISSUE TITLE
Bucardo cannot automatically synchronize lost nodes

### ISSUE THREAD

**Issue by hom7** [bucardo/bucardo#186]
Bucardo5.5.0
1, master (bucardo)    2, master

Test: close 2 postgresql
Write data in 1 and then reopen 2 postgresql. At this time, the data cannot be automatically synchronized from 1 to 2postgresql. 

Is there a solution?

**Comment by machack666** [comment]
You may need to activate the node and/or restart the Bucardo daemon for it to detect the node has come back.

I.e.,:

  $ bucardo activate sync my_sync
  $ bucardo restart
  $ bucardo status

You can see for sure if it has marked the sync as inactive via:

  $ bucardo list sync my_sync

HTH,

David

**Comment by hom7** [comment]
hi，
I simulated the drop for the 5432 port packet
 (iptables -A INPUT -p tcp --dport 5432 -j REJECT --reject-with tcp-reset)

The result is the same as my active shutdown of postgresql, which is equivalent to network packet loss.
Then also need to actively restart? Https://github.com/bucardo/bucardo/issues/105

Is there any other better solution?
