### ISSUE TITLE
Bucardo cannot automatically synchronize lost nodes -

### ISSUE THREAD

**Issue by hom7** [bucardo/bucardo#187]
hi，
I simulated the drop for the 5432 port packet
(iptables -A INPUT -p tcp --dport 5432 -j REJECT --reject-with tcp-reset)

The result is the same as my active shutdown of postgresql, which is equivalent to network packet loss.
Then also need to actively restart? Https://github.com/bucardo/bucardo/issues/105

Is there any other better solution?

**Comment by suharevA** [comment]
I wrote a script to track server status. As soon as the connection is resumed, the script makes the bucardo restart command. Sync is restored

**Comment by walidelhawari** [comment]
suharevA  can i have this script please 
 my email is walid@arkanit.ly

**Comment by fredcvpetten** [comment]
> Eu escrevi um script para rastrear o status do servidor. Assim que a conexão é retomada, o script faz o comando bucardo restart. A sincronização foi restaurada

Hi, could you please make it available? email frederico@ati.com.br

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
