### ISSUE TITLE
Bucardo.org online documentation links broken

### ISSUE THREAD

**Issue by tk421** [bucardo/bucardo#188]
Hi,

I am currently reading the documentation and I am finding quite a lot of links broken. Example:
 - https://bucardo.org/Bucardo/bucardo.html has references to "herd" which points at https://bucardo.org/Bucardo/herd which a broken link
 - https://bucardo.org/herd/ has a link to "sync" that is broken too.

I have found other examples, but I guess that it would suffice to find and fix the problem.

Regards,
Ruben

**Comment by chibicitiberiu** [comment]
I can't find any detailed manual, other than the "FAQ" page, the "Overview" page and the tutorials. These are not very helpful. Look at the documentation [slony](http://www.slony.info/documentation/2.2/index.html) has, this is the kind of documentation I expect.

**Comment by hasegeli** [comment]
We added the links.  But the documentation is still in sad state.  Any help is appreciated:

https://github.com/bucardo/bucardo_org
