### ISSUE TITLE
Failed to add sync, function problem

### ISSUE THREAD

**Issue by jozwior** [bucardo/bucardo#190]
Hello,

I have issues with adding database to sync. DB versions: PostgreSQL 9.6.8 (RDS), Jump system: Ubuntu18.04 LTS, bucardo version: 5.4.1.

When trying run this command: 
`bucardo add sync db_sync relgroup=copying_herd dbs=source_db:source,dest_db:target onetimecopy=1`
I receive this error:
```bash
WARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=dc_sourcedb;host=xxx.aaa.xyz;port=5432 at line 126.
Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::db do failed: ERROR:  function search_string(text) does not exist
LINE 5:             array_agg(search_string(x)),
                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:
  SELECT
    coalesce(
        array_to_string(
            array_agg(search_string(x)),
            '|'
        )::text,
        ''
    )
  FROM unnest($1) x

CONTEXT:  SQL function "flatten_text_array" during inlining at line 126. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at /usr/bin/bucardo line 4612.
```

Function `search_string` exist and I can run this function from psql command line.

**Comment by jozwior** [comment]
It was issue with `search_path` on my site.

**Comment by dexios1** [comment]
> how do you fix this?
> 
> got same issue
> 
> ```
> WARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=xxy;host=aayaya..us-west-2.rds.amazonaws.com;port=5432 at line 833.
> Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::db do failed: ERROR:  cannot delete from table "bucardo_delta_targets" because it does not have a replica identity and publishes deletes
> HINT:  To enable deleting from the table, set REPLICA IDENTITY using ALTER TABLE. at line 833. at line 30.
> CONTEXT:  PL/Perl function "validate_sync" at /usr/local/bin/bucardo line 4670.
> ```

I got the same error. Yet to find a solution however, I saw that someone's had this issue in the Bucardo mailing list: https://bucardo.org/pipermail/bucardo-general/2020-January/003175.html

As a step to verify, he recommends, login in with the indicated rds_superuser role and verify that you can issue:
```sql
    BEGIN; SET session_replication_role = replica;
```

I'm able to issue the command, but unsure how to proceed.
```
[bucardo=# BEGIN; SET session_replication_role = replica;
BEGIN
SET
```

@pgguru @machack666 think you could give this a look?
