### ISSUE TITLE
Will bucardo be responsible for data size increase in db size? 

### ISSUE THREAD

**Issue by shubham-chegg** [bucardo/bucardo#191]
I have a question, will bucardo be able to increase overall size of db?

In dec’18, we migrated to RDS from EC2 postgres, using bucardo replication. But due to some reasons, we had to stop using that and put the task in backlog. We stopped the bucardo syncing, and left the system as it is. Now after 3 months after we stopped it, we are facing an high increase rate in db size as compared to duration before. 

we suspect bucardo is responsible because the time it all started matches with the date we stopped bucardo. 

We have following logs when run on db server:

**Log.bucardo**
(53367) [Tue Jan 22 16:00:32 2019] MCP End of cleanup_mcp. Sys time: Tue Jan 22 16:00:32 2019. Database time: 2019-01-22 16:00:32.391908+00
(53367) [Tue Jan 22 16:00:32 2019] MCP Exiting
*** Error in `Bucardo VAC.': double free or corruption (!prev): 0x0000000002997e50 ***

**root@db:~# bucardo status;**
Fri Apr  5 09:47:04 UTC 2019

 Name                      State    Last good               Time            Last I/D    Last bad                Time          
=========================+========+=======================+===============+===========+=======================+===============
 sync_db1         | Good   | Jan 10, 2019 15:10:50 | 2034h 36m 14s | 0/0       | none                  |               
 sync_db2      | Good   | Jan 22, 2019 16:00:20 | 1745h 46m 44s | 0/1       | none                  |               
 sync_db3        | Good   | Jan 10, 2019 15:10:51 | 2034h 36m 13s | 0/0       | none                  |               
 sync_db4           | Bad    | Jan 22, 2019 11:57:44 | 1749h 49m 20s | 24/24     | Jan 22, 2019 16:00:29 | 1745h 46m 34s 
 sync_db5 | Bad    | none                  |               |           | Jan 22, 2019 16:00:31 | 1745h 46m 33s 
 sync_db6       | Good   | Jan 22, 2019 16:00:30 | 1745h 46m 34s | 0/0       | none                  |               
 sync_fb7 | Good   | Jan 22, 2019 16:00:29 | 1745h 46m 35s | 0/6       | none                  |               
 sync_db8      | Good   | Jan 10, 2019 15:10:51 | 2034h 36m 13s | 0/0       | none                  |               

> As you can see Last good is of Jan 22, which is the date we stopped it. There is an increase in every db, but the dbs db4 and db5, are increasing with higher speed.

**root@db:~# bucardo list syncs**
Sync "sync_db1"           Relgroup "relgroup_db1"          [Active]
  DB group "dbgroup_db1" dest_db1:target source_db1:source
Sync "sync_db2"       Relgroup "relgroup_db2"      [Active]
  DB group "dbgroup_db2" dest_db2:target source_db2:source
Sync "sync_db3"         Relgroup "relgroup_db3"        [Active]
  DB group "dbgroup_db3" dest_db3:target source_db3:source
Sync "sync_db4"            Relgroup "relgroup_db4"           [Active]
  DB group "dbgroup_db4" dest_db4:target source_db4:source
Sync "sync_db5"  Relgroup "relgroup_db5" [Active]
  DB group "dbgroup_db5" dest_db5:target source_db5:source
Sync "sync_db6"        Relgroup "relgroup_db6"       [Active]
  DB group "dbgroup_db6" dest_db6:target source_db6:source
Sync "sync_db7"  Relgroup "relgroup_db7" [Active]
  DB group "dbgroup_db7" dest_db7:target source_db7:source
Sync "sync_db8"       Relgroup "relgroup_db8"      [Active]
  DB group "dbgroup_db8" dest_db8:target source_db8:source

> This makes me believe that all syncs are active, but we are sure that bucardo is not pushing it anywhere. 

Also there is a slave server to this database, on which there is no bucardo service running but size is similar to master, which put us in strong doubts about the reason of the cause. 

So my questions here is:
1. Will the above scenario possible?
2. Is there any command, to see if there are any locally stored replication files? if yes, where are they
3. Can I remove the above files through some command, or manually?

PS: our dba is not here, so need help.

**Comment by machack666** [comment]
Yes, if you only stop Bucardo but do not remove it it will continue to track all changes to your tables.  Since the Bucardo daemon is not running, it will never remove any rows and your database will bloat.

If you are never going to use Bucardo again and just want to remove any vestiges, you will need to remove triggers and the delta tables; all of this is in the `bucardo` schema on each database.  If you run the following command on each of the source databases, this should clear it up.  (Please note that this *will* take a lock on all of the replicated tables, so it could cause some issues in your environment.)

`DROP SCHEMA bucardo CASCADE;`

HTH,

**Comment by machack666** [comment]
Note that this will remove *all* bucardo stuff from this database; if you need to only remove a subset or from only some parts of the nodes you may need a different approach.

**Comment by shubham-chegg** [comment]
Thanks for the prompt reply, as if I understood it correct. if I need to remove bucardo completely I need to remove schema from all the replicating db. Please correct me If I am wrong.

But what about “Active” bucardo syncs? Do I need to perform any action there, or its fine.

Also if I don’t want to delete it completely, what options/ways do I have? Kindly provide details of that.

Thanks,
Shubham Jhandei

**Comment by shubham-chegg** [comment]
Will
