### ISSUE TITLE
Need to recreate /var/run/bucardo after reboot before bucardo start

### ISSUE THREAD

**Issue by sebalaini** [bucardo/bucardo#193]
After a reboot of the server with bucardo running, I cannot stop bucardo because it doesn't find the folder

https://github.com/bucardo/bucardo/issues/99

I'm using Bucardo 5.5.0

**Comment by rojspencer** [comment]
This is probably systemd purging the directory.

See: https://unix.stackexchange.com/questions/381571/what-would-likely-cause-directories-in-var-run-to-disappear-not-be-created-on
And: https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#

**Comment by sebalaini** [comment]
sorry, I'm not working anymore on that project. I'll close the issue.
