### ISSUE TITLE
How many tables are synchronized by a single bucardo synchronization process

### ISSUE THREAD

**Issue by bucardo111** [bucardo/bucardo#198]
When the number of tables for a single synchronization process reaches 155，the synchronization process stops synchronization，is this a bug?

In addition, it automatically stops and restarts when nothing is done manually, wondering when such a reboot might occur.
(bucardo5.4.1 + postgresql 9.5.5+centos7.4)

**Comment by machack666** [comment]
There should not be a hard limit like what you describe. What shows up on the logs?

**Comment by bucardo111** [comment]
The log shows no errors or warnings. When i increase the number of synchronized tables to 155, the synchronized data will stop. After a restart of synchronization, the data that changed before the restart is synchronized to the target database, but the data that changed after the restart is not synchronized unless restarted again.
However, after removing the synchronization of any table, the synchronization is normal. All tables have primary keys and data volumes in the millions and tens of millions levels.

**Comment by machack666** [comment]
Are you creating new syncs or adding to an existing one? Are you able to see the bucardo triggers on all of the relations? What is max_locks_per_transaction?

**Comment by bucardo111** [comment]
Is added to an existing sync, and i'm able to see the bucardo triggers on all of the relations. The value of max_locks_per_transaction is 64 by default.But in another synchronization process, where I added more than 200 tables, the data synchronization was normal, with the only difference being that the tables had much less data. So I was wondering what the problem was

**Comment by bucardo111** [comment]
Also, does a name too similar to sync affect synchronization? There are two syncs on the same port, sync_his and sync_ihis

**Comment by machack666** [comment]
No, that should not affect anything.

**Comment by machack666** [comment]
When you make a change on this cluster do you see the corresponding rows in the delta tables?  What are you using to bootstrap the table data?  Is it possible the initial copy of table data is still in process?

**Comment by bucardo111** [comment]
Yes, when I update a row of data, the corresponding data can be found in bucardo.delta.The same dump data is imported for the source and destination databases, so the initial data is the same.I think it might be some special combination of conditions that triggered some kind of bug.Data synchronization is normal with different databases and different syncs under the same conditions,or when I upgraded bucardo to 5.5.0, the problem just disappeared.

**Comment by bucardo111** [comment]
Another question. Bucardo5.5.0 shows logs that are shorter than 5.4.1. Bucardo5.5.5 only shows errors or warnings, but bucardo5.4.1 shows data changes caused by DML operations. Is there a problem with my configuration or is log display simplified?

**Comment by machack666** [comment]
Well if this issue is no longer present in 5.5.0 there must have been a bug which was fixed. :)

I don't recall offhand if the logging levels changed but that would not surprise me; does not seem like an error, just a change in behavior.

Can we close this issue now?

**Comment by bucardo111** [comment]
Of course you can close this issue. 
Looking  forward to the new bucardo update.
