### ISSUE TITLE
[Feature Request] Option for TABLESPACE use in creation of Source Bucardo tables

### ISSUE THREAD

**Issue by qops1981** [bucardo/bucardo#199]
Greetings Maintainers,

It would be great if we could submit a TABLESPACE for source bucardo tables (delta, track, etc.). Many of the EC2 Postgres DB's that I am working on Migrating offer local SSDs. As it is I am going to try and figure out on how to migrate these into a tablespace manually. My main concern there is the interaction with placed triggers. But figured it would be nice if this was just done during creation. The reason I would like to use the SSD is due to the IO and CPU overhead the replication process cause on very active tables. 

I am also considering (if I can figure out) on how to modify the project with said option and then submit a PR but Perl is not one of the languages I am familiar with.

Thanks!

**Comment by machack666** [comment]
It would probably be sufficient to set the tablespace of the bucardo schema on creation time and everything else should support that. One tricky part would be how to set that on a per-db setting and if you'd expect that to already exist or if you'd create it as part of the process. How do you see that working?

**Comment by qops1981** [comment]
Hey Mac,

As far as I am aware per Postgres Docs there is at least an absence of direction on that being an available function of the `( ALTER | CREATE ) SCHEMA` commands.

For the Per DB issue, I might imagine the user would create the `TABLESPACE` on the DB they choose, then in Bucardo when adding the DB's there could be an option for `TABLESPACE`. Since ultimately tablespace's don't matter to anything but the Postgres DB it would only be an indicator to the Bucardo service to create the tables on the DB in question in said tablespace.

Example:
```bash
# Manually Create TABLESPACE Here..
# Note: Last Parameter, something along these lines?
bucardo add db <source_name> dbname=<dbname> host=<ec2 host> user=<username> pass=<password> tablespace=<tablespace_name>
```

**Comment by qops1981** [comment]
Hey Mac,

Here is another option ( if its not what you were already suggesting ). I figured out that Postgres has a `default_tablespace` config option. In the docs it says it does not effect temp table and other working datasets. so here is what I did:

* Formatted the EC2 Instance Store in `ext4` _( Provided Direct Attach SSD )_
  * Disables Journaling at format time _( recommended from various sites )_
  * Mounted with `noatime,discard` _( recommended from various sites )_
* Created a Directory in `/mnt/` _( could be anywhere really )_
  * Mounted the Instance Store there.
* Created a `TABLESPACE` targeting a directory I made above on the EC2's Instance Store
  * Changed the ownership of that tablespace to our standard user
* Changed the `default_tablespace` config in `postgresql.conf ` to the tablespace created above
  *  Reloaded the config `SELECT pg_reload_conf();`
* Configured Bucardo for replication from the source where I made all the changes above to the new RDS instance I created.
  * Add DB's, Tables, Syncs, Etc.
  * Bucardo Creates Tables on Source
  * Confirm All tables are in the "bucardo" tablespace created above
* Revert my Config change in `postgresql.conf ` so there is no longer a `default_tablespace`
  * Reload the config `SELECT pg_reload_conf();`
  * Check to make sure the is no `default_tablespace` anymore `SHOW default_tablespace;`
* Begin / Kick replications off

As it stands now all my bucardo tables are on the EC2 instance store and I am no longer suffering from IO wait. This is the 4th Migration I am doing and I wish I had thought of this from the beginning!

Understandably not every will have the Luxury of direct attached SSD extra from their main volume. But if you do this is a pretty good option. I will update if I learn anything else from this process.
