### ISSUE TITLE
MCP Warning: Killed (line 7185): DBD::Pg::st execute failed: ERROR:  invalid name syntax at /usr/local/share/perl5/Bucardo.pm line 7185.

### ISSUE THREAD

**Issue by Maytrovato** [bucardo/bucardo#204]
Hello, I got this problem while starting bucardo. 

```
(25402) [Mon Nov 11 11:52:31 2019] MCP   Inspecting source table "public.table_1" on database "local_serv5"
(25402) [Mon Nov 11 11:52:31 2019] MCP    Inspecting target table "." on database "local_serv4"
(25402) [Mon Nov 11 11:52:31 2019] MCP Warning: Killed (line 7185): DBD::Pg::st execute failed: ERROR:  invalid name syntax at /usr/local/share/perl5/Bucardo.pm line 7185.
(25402) [Mon Nov 11 11:52:33 2019] MCP End of cleanup_mcp. Sys time: Mon Nov 11 11:52:33 2019. Database time: 2019-11-11 11:52:33.03855-05
```

And this is line 7185:
`            $sth->execute("$RS.$RT");`

This is my Perl version
```
[root@my_host bucardo-master]# perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 39 registered patches, see perl -V for more detail)

```

And BDB module version
`perl-DBD-Pg-2.19.3-4.el7.x86_64`

EDIT: Looks like there a null var for the scheme.database target

`/usr/local/share/perl5/Bucardo.pm`
`            $self->glog(qq{   Inspecting target $g->{reltype} "$RS.$RT" on database "$dbname"}, LOG_NORMAL);`

`/var/log/bucardo/log.bucardo`
```
(10530) [Tue Nov 12 11:37:16 2019] MCP   Inspecting source table "public.contacts" on database "cilcpcxd7568"
(10530) [Tue Nov 12 11:37:16 2019] MCP    Inspecting target table "." on database "cilcpcxd7567"

```

Thanks in advance.

**Comment by Paradox2019** [comment]
Same error here, need help. :(

**Comment by Paradox2019** [comment]
Hey

> 
> 
> Hello, I got this problem while starting bucardo.
> 
> ```
> (25402) [Mon Nov 11 11:52:31 2019] MCP   Inspecting source table "public.table_1" on database "local_serv5"
> (25402) [Mon Nov 11 11:52:31 2019] MCP    Inspecting target table "." on database "local_serv4"
> (25402) [Mon Nov 11 11:52:31 2019] MCP Warning: Killed (line 7185): DBD::Pg::st execute failed: ERROR:  invalid name syntax at /usr/local/share/perl5/Bucardo.pm line 7185.
> (25402) [Mon Nov 11 11:52:33 2019] MCP End of cleanup_mcp. Sys time: Mon Nov 11 11:52:33 2019. Database time: 2019-11-11 11:52:33.03855-05
> ```
> 
> And this is line 7185:
> ` $sth->execute("$RS.$RT");`
> 
> This is my Perl version
> 
> ```
> [root@my_host bucardo-master]# perl --version
> 
> This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
> (with 39 registered patches, see perl -V for more detail)
> ```
> 
> And BDB module version
> `perl-DBD-Pg-2.19.3-4.el7.x86_64`
> 
> EDIT: Looks like there a null var for the scheme.database target
> 
> `/usr/local/share/perl5/Bucardo.pm`
> ` $self->glog(qq{ Inspecting target $g->{reltype} "$RS.$RT" on database "$dbname"}, LOG_NORMAL);`
> 
> `/var/log/bucardo/log.bucardo`
> 
> ```
> (10530) [Tue Nov 12 11:37:16 2019] MCP   Inspecting source table "public.contacts" on database "cilcpcxd7568"
> (10530) [Tue Nov 12 11:37:16 2019] MCP    Inspecting target table "." on database "cilcpcxd7567"
> ```
> 
> Thanks in advance.

Hey man, i think that is an bug. I´ve downloaded the latest stable release and didn´t cloned the source. built it and then it works well. https://github.com/bucardo/bucardo/archive/5.5.0.zip

**Comment by Paradox2019** [comment]
You can just replace the bucardo.pm with the one from the archive-release.

**Comment by Maytrovato** [comment]
> You can just replace the bucardo.pm with the one from the archive-release.

It worked like a charm! thank you so much! I'm going to close this issue
