### ISSUE TITLE
MCP Warning: Killed (line 7185): DBD::Pg::st execute failed: ERROR:  invalid name syntax at /usr/local/share/perl/5.22.1/Bucardo.pm line 7185.

### ISSUE THREAD

**Issue by Paradox2019** [bucardo/bucardo#205]
Hey guys i got the following error code in my bucard logfile
(4853) [Mon Nov 18 14:28:17 2019] MCP   Inspecting source table "public.affiliation" on database "z1"
(4853) [Mon Nov 18 14:28:17 2019] MCP    Inspecting target table "." on database "z2"
(4853) [Mon Nov 18 14:28:17 2019] MCP Warning: Killed (line 7185): DBD::Pg::st execute failed: ERROR:  invalid name syntax at /usr/local/share/perl/5.22.1/Bucardo.pm line 7185.
(4853) [Mon Nov 18 14:28:19 2019] MCP End of cleanup_mcp. Sys time: Mon Nov 18 14:28:19 2019. Database time: 2019-11-18 14:28:19.525531+01

I have perl 5, version 22 subversion 1 installed

Can you Help me ? :(

**Comment by Maytrovato** [comment]
You can now close this issue. 

Solved at https://github.com/bucardo/bucardo/issues/204
