### ISSUE TITLE
Postgres 12 Support?

### ISSUE THREAD

**Issue by supersexy** [bucardo/bucardo#206]
What about support for Postgres 12? 

It would be really very, very helpful if you would like to add the supported version of Postgres to the Readme - I only understood by some info in the [changelog](https://github.com/bucardo/bucardo/blob/c8a310d63e09d8b497fce81e510f220db074e573/Changes#L35) that bucardo seems not to be comptible with all versions out of the box - so it seems to be a very important info that you should not hide. 

Thank you very much!

**Comment by machack666** [comment]
Hi, I am unaware of any specific issues with PostgreSQL 12; are you running into any particular issues using it, or just extrapolating from previous compatibility fixes?

**Comment by supersexy** [comment]
Yes, yes, just extrapolating, full of fear of hitting the one incompatibility bug. :) 
I guess it will be ok if you see no problems! Wish you nice holidays!
