### ISSUE TITLE
Document for version 5

### ISSUE THREAD

**Issue by robin8588** [bucardo/bucardo#208]
Hi ,
I am try to use this great project ,but when I following the document ,it make me confused .
like running :
bucardo add sync benchdelta source=alpha targetdb=test2 type=pushdelt
return error:
Unknown option 'source'

So ,I don`t know how to set source ,how to set target ,how to set sync type,
Is there a document ,can let me know :
how to Monitoring tye sync
what is the restrictions
......

thanks

**Comment by machack666** [comment]
Hi, can you let me know which page you saw this on?  That looks like an old-style Bucardo 4 syntax.

The general approach is this:

1. Add dbs.
2. Define dbgroups for source/target definitions.
3. Add tables into a relgroup.
4. Create sync that uses the dbgroup and the relgroup.

So this will look something like this:

```
$ bucardo add db db1 ...
$ bucardo add db db2 ...
$ bucardo add dbgroup thedbs db1:source db2:target # can also be source, for multimaster, and support arbitrary number of servers
$ bucardo add all tables relgroup=thetables
$ bucardo add sync thesync relgroup=thetables dbgroup=thedbs
```

HTH,

**Comment by robin8588** [comment]
thank @machack666 
I saw the code from  
https://bucardo.org/Bucardo/Installation.html
and 
https://bucardo.org/Bucardo/pgbench_example.html

I can success sync with your code

**Comment by jpjofre94** [comment]
@machack666 I'm having the same issue than @robin8588. As you said, documentation on website seems outdated.

**Comment by axshen** [comment]
Thanks @machack666 I was able to get the [pgbench example](https://bucardo.org/Bucardo/pgbench_example.html) working with your code.

**Comment by jonjensen** [comment]
I just extensively reworked the [pgbench example](https://bucardo.org/Bucardo/pgbench_example) too, running through it all from scratch myself.
