### ISSUE TITLE
Release Bucardo 5.6.0?

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#209]
Lots of useful improvements we could use. Anything preventing bundling up and releasing 5.6.0 (or 5.5.1 if you'd rather)?

**Comment by theory** [comment]
🐘😭

**Comment by machack666** [comment]
If you can test/verify, this will assist in getting this formally released.

**Comment by theory** [comment]
Passed the request on to our Postgres DevOps to test, thanks!

**Comment by machack666** [comment]
Hi, any feedback here?  Were they able to get things going to your knowledge or do they need more time?

**Comment by theory** [comment]
I believe the team will have some bandwidth to test it this week (finishing a big upgrade right now, so trying to minimize the variables in play). I'll give you a holler when I know more, hopefully just a .

**Comment by theory** [comment]
We got it installed and got our first error:

```
WARN (258499) [Tue Feb 11 00:11:04 2020] MCP Warning: Killed (line 7372): DBD::Pg::db selectall_arrayref failed: ERROR:  syntax error at or near ","
LINE 9:              AND (conrelid IN (,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
                                       ^ at /usr/local/perl/lib/site_perl/Bucardo.pm line 7372.
```

**Comment by theory** [comment]
I confess I don't understand the reason for this error, however. That code path hasn't changed since 5.5.0 AFAICT.

**Comment by theory** [comment]
FYI:

```
Unparsable version '1.2.4' for prerequisite DBIx::Safe treated as 1.2 (CPAN::Meta::Requirements not available) at Makefile.PL line 9.
```

**Comment by machack666** [comment]
Perl version?

**Comment by theory** [comment]
5.16.3

**Comment by theory** [comment]
Fixed the OID error in 189bef2.

**Comment by machack666** [comment]
@theory is the "OID error" you mention the issue above where it's not finding the `conrelid`?

**Comment by theory** [comment]
Yes, #211 fixes the error with the comma-delimited empty OIDs compared to the `conrelid` column.

**Comment by machack666** [comment]
Anything else outstanding that you're aware of?

**Comment by theory** [comment]
No. We ran some tests in our QA environment. The log timer format works well, as do the schema-qualified table lookups for configuring custom codes. The engineer told me:

> We have replication, the custom code, I didn't go looking for corner cases.
>  I'm doing what QA rarely does, I'm trusting that most existing functionality isn't broken.

I assured her that she covered the changes since 5.5.0; there aren't many, fortunately. I do think it would be helpful to merge #212, though.

**Comment by machack666** [comment]
Merged #212, going to skim through for low-hanging fruit.

**Comment by theory** [comment]
🔔 🔛

**Comment by machack666** [comment]
Released 2020/02/28.
