### ISSUE TITLE
Replication failure using 5.4.1-1

### ISSUE THREAD

**Issue by spchinna25** [bucardo/bucardo#210]
replication not working in long run when configured with bucardo 5.4.1-1 in my 1+1 Master setup

**Comment by spchinna25** [comment]
Is there any known bug fixed related to this in 5.5 ?

**Comment by machack666** [comment]
Hi, @spchinna25,

If you are running into specific issues, please use the mailing list to report: https://bucardo.org/mailman/listinfo/bucardo-general

Also, we will need a lot more information to do anything useful with this report; are you getting error messages from the `log.bucardo` file, PostgreSQL logs, etc.  The first step would be to try the latest version of Bucardo, which is 5.5.0.

Best,

David
