### ISSUE TITLE
try to connect and sync to a remote postgres istance

### ISSUE THREAD

**Issue by LucaPaterlini** [bucardo/bucardo#214]
hello,
I have set up 2 virtual machines and I am trying to keep 2 instances of a database in sync.

I have added the connection to the remote PostgreSQL instance.
sudo bucardo add db vmmetrics_server_dev  dbname=metrics_server_dev host=192.168.1.244 user=postgre pass=postgres

I have checked the second vm is available for the first one where I have installed bucardo at 192.168.1.244 via connecting with psql.

then with my surprise this is the response I am getting while I am tring to add the tables of the second postgresql instance.

sudo bucardo add all tables db=vmmetrics_server_dev  --herd=beta  --verbose
Sorry, no tables were found
Relgroup already exists: beta
New tables added: 0

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on.
