### ISSUE TITLE
Could not find the bucardo.schema file! Straight after installing.

### ISSUE THREAD

**Issue by depesz** [bucardo/bucardo#215]
I'm using local perl dir, created by:

`perl -Mlocal::lib`

It did set these env variables:

```
PATH="/home/pgtest/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/pgtest/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/pgtest/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/pgtest/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/pgtest/perl5"; export PERL_MM_OPT;
```

I did install of Bucardo 5.6, and it installed in /home/pgtest/perl5:

```
=$ find perl5/ | grep -i bucardo
perl5/bin/bucardo
perl5/usr/local/share/bucardo
perl5/usr/local/share/bucardo/bucardo.schema
perl5/man/man1/bucardo.1pm
perl5/man/man3/Bucardo.3pm
perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Bucardo
perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Bucardo/.packlist
perl5/lib/perl5/Bucardo.pm
```

But when trying to run "bucardo install" - it complains:

```
=$ bucardo install --piddir=/home/pgtest/tmp
This will install the bucardo database into an existing Postgres cluster.
Postgres must have been compiled with Perl support,
and you must connect as a superuser

Could not find the bucardo.schema file!
```

Strace showed that it looks only in /usr/local/share/bucardo/bucardo.schema and /usr/share/bucardo/bucardo.schema but why doesn't it look in a place it installed?

**Comment by machack666** [comment]
Yes, this should look where installed; from what I know, this is the first time I've heard of someone installing it from `local::lib` (as it would have had this issue then too).

Will see about a patch for this.

**Comment by machack666** [comment]
@depesz pushed a likely fix in cb3315d; can you verify this works for you?

**Comment by depesz** [comment]
Looks like it works. One question, though - why add usr/local there?

I would assume that if script is in X/bin, then it's share things are in X/share/ - just like X/lib, or anything like this.

We can close the bug, as it clearly works now, and the location of files is less important for now.

Thanks a lot.

**Comment by machack666** [comment]
I was just basing it on the installation paths you mentioned, so 🤷‍♂.  I haven't used `bucardo` with `local::lib` though, so can't promise it makes sense.  (Do let me know if you run into any additional issues though...)
