### ISSUE TITLE
Invalid format returned by custom query (if using a function)

### ISSUE THREAD

**Issue by joaormp** [bucardo/bucardo#218]
Hi guys,

I have a problem, I have a simple function to return data but when using the custom query Invalid format returned by a custom query:
(host:127.0.0.1) Invalid format returned by custom query | time=2.45s ...

Can anyone help with this issue?

Thanks in advance

**Comment by machack666** [comment]
Hi @joaormp can you provide some details here?  Also the output you've provided makes me wonder if this is related to `check_postgres`, not `bucardo` proper.

**Comment by joaormp** [comment]
Hi, 
It's solved, when I call the function we have to have an alias result.
Now it's working
solution:     --action=custom_query --query="select [functions_Name]() as result"

**Comment by joaormp** [comment]
Hi,
It's solved, when I call the function we have to have an alias result.
Now it's working
solution: --action=custom_query --query="select functions_Name as result"
