### ISSUE TITLE
Exact working scenario of conflict strategy "bucardo_latest" ?

### ISSUE THREAD

**Issue by sangleemester** [bucardo/bucardo#222]
Hi everybody,

I'm trying to create a master-master replication with bucardo for a geo-redundant environment.
Both site's applications are using their own DB instances by default, in case the connection between the sites are down, both sites remain operational, but it's also necessary to share and sychronise the DB changes happened on both sites while the network connection was down.

I set the master-master replication, chose conflict_strategy=bucardo_latest (if both sites update the same row(s), the newer data will remain).

I thought, bucardo_latest works like this:
- as conflict handling starts, for the first matching (conflicted) rows in delta tables bucardo decides which side's change happened later, and  the other sites DB will be updated.
- jumps to the next matching rows, checks txntime for this rows again, decides again, makes the update
- etc.

...but instead, I see it checks ALL of the matching rows at once, finds the VERY LAST update happened in any DB instance, and it updates all the "loser" DB's matching rows, even if all the conflicted rows were updated later on the loser's side but the last one.

See the following example:

```
delta_db1_testTable
id     txntime
21	2020-11-23 12:03:14 (later)
22	2020-11-23 12:03:14 (later)
23	2020-11-23 12:03:14 (later)
25	2020-11-23 12:03:23 (sooner)

delta_db2_testTable
id     txntime
21	2020-11-23 12:02:53 (sooner)
22	2020-11-23 12:02:53 (sooner)
23	2020-11-23 12:02:53 (sooner)
25	2020-11-23 12:03:31 (later)
```

In my expectations, this should be updated like this:

id    direction of updates
21   db1 >>> db2
22   db1 >>> db2
23   db1 >>> db2
25   db1 <<< db2

But actually it runs like this:

id    direction of updates
21   **db1 <<< db2**
22   **db1 <<< db2**
23   **db1 <<< db2**
25   db1 <<< db2

Is this the right working method for bucardo_latest?
Is there any settings to declare for bucardo to do this evaluation row by row (time cost doesn't really matters in this case), not at once for all the conflicts?

Thanks!

Kind regards,
Gabor

**Comment by machack666** [comment]
Hi @sangleemester,

From a code review, it *does* look like the behavior you describe is what the code does; I assume that the basic assumption here is that replication is happening regularly, so anything that ends up in a conflict would have had previous rows copied over in a prior sync event.  (For the record, I also am a bit surprised that this is the way this works, as I would have expected things to be processed on a txntime-by-txntime basis individually.)

Is your sync set up with `autokick`?  I can see that if you have a time-based sync that these replication events would not line up with regular sync events and you'd definitely end up in this situation.  If you turned off autokick, then turning that on might help keep up-to-date.

It is also possible that you might be able to write a custom conflict handler; my suspicion is that this would still not end up handling things row-by-row. 

I don't think we can support this approach as-is without making some additional patches to how this is handled; it might be that we could select all deltas per group of txntime and processing each one individually before finally commiting the overall aggregate changes, but this seems to be something that would cause some performance issues in the case you *don't* need this special conflict handling *and* you have a large number of changes.

Best,

David
