### ISSUE TITLE
is fullcopy deprecated?

### ISSUE THREAD

**Issue by why-el** [bucardo/bucardo#228]
Trying to use `fullcopy` for non-primary key tables: 

```
./bucardo add sync NAME dbs=DB1, DB2 relgroup=DB1toDB2nonpkfullcopy type=fullcopy
Unknown option 'type'
   add sync:
      bucardo add sync name relgroup=xxx dbs=xxx
```

am I mistyping something? Or is the option deprecated? It is still [mentioned](https://bucardo.org/Bucardo/object_types/fullcopy) in the docs as of 2020.

**Comment by hasegeli** [comment]
I think it's controlled by the "onetimecopy" option on the latest version.

The documentation is unfortunately outdated.  We are working on fixing it.

You can read about the options using "bucardo help add sync".

**Comment by why-el** [comment]
`onetimecopy` (run as part of `./bucardo add sync NAME dbs=DB1, DB2 relgroup=DB1toDB2nonpkfullcopy onetimecopy=2`) complains with: 

```
Failed to add sync: DBD::Pg::st execute failed: ERROR:  Table "public.TABLE" must specify a primary key! at line 119. at line 30.
```

This is what's confusing. `fullcopy` was the solution to small tables missing primary keys (short of adding primary keys or unique indexes), and that option is gone, so I would suspect `onetimecopy` to be a drop in replacement, but it's not.

**Comment by hasegeli** [comment]
I tracked this down in the code and find out how to do it.  You need to create `dbgroup` using `fullcopy` role.  Here is an example:

```
bucardo add db db1 dbname=db1
bucardo add db db2 dbname=db2
bucardo add dbgroup nopk db1:source db2:fullcopy
bucardo add sync nopk dbgroup=nopk tables=table_without_pk onetimecopy=2
bucardo kick nopk
```

I confirmed on master that this works.  However, I think it's broken on on the last release.  We'll make sure this is documented, and look into releasing a new version.

**Comment by why-el** [comment]
Ah, thank you for lookinng into it. 👍 I have since decided it was easier to just add unique indexes, but good to know that there will be a fix.

**Comment by hasegeli** [comment]
I submitted documentation fixes:

https://github.com/bucardo/bucardo/pull/232
https://github.com/bucardo/bucardo_org/pull/16

**Comment by why-el** [comment]
thank you @hasegeli 👍
