### ISSUE TITLE
Does Bucardo support 'SELECT ... FOR UPDATE' ?

### ISSUE THREAD

**Issue by denismatveev** [bucardo/bucardo#231]
Hey!

I faced the problem building airflow cluster. To launch multiple instances they use 'SELECT ... FOR UPDATE'. 
I tried to build the cluster with postgres-13 in multi master cluster. And got errors.

Versions:
- PostgreSQL 13.2
- Bucardo  5.6.0
- Ubuntu 20.04

Do you have plans to implement such feature in the future? If so, which release will contain this?

**Comment by hasegeli** [comment]
I couldn't understand what you meant by 'SELECT ... FOR UPDATE' support.

Bucardo works with INSERT/UPDATE/DELETE triggers.  It records changes rows and replicates them to the other instances.  SELECT ... FOR UPDATE wouldn't trigger anything.

**Comment by turnstep** [comment]
It would be helpful if you could show the exact errors that were produced.

**Comment by denismatveev** [comment]
Hey! I'm afraid I cannot provide any additional information, I gave up using burardo, but there is my question at airflow github:
