### ISSUE TITLE
Unable to Add Database After Bucardo Install

### ISSUE THREAD

**Issue by Austinreedthomas** [bucardo/bucardo#241]
After a successful bucardo install on port 5432, dbname=postgres, and dbuser=postgres via RPM installation, I'm trying to run the command `bucardo add db db_hostname_dbname` on my master node and getting the error `ERROR: relation "bucardo.bucardo_config" does not exist`
`SELECT setting FROM bucardo.bucardo_config WHERE LOWER(name).. ^ at /sbin/bucardo line 548`

If I manually enter psql as the superuser postgres, a bucardo database exists and contains a table named bucardo_config.

Bucardo Version: 5.6
PostgreSQL Version: 11.5

Dependency Versions:
perl-CGI: 3.63
perl-Sys-Syslog: 0.33
perl-Pod-Parser: 1.61
perl-Encode-Locale: 1.03
perl-DBD-Pg: 2.19.3
perl-Test-Simple: 0.98
postgresql-plperl: 9.2.24
perl-boolean: 0.30
perl-DBIx-Safe: 1.2.5
perl-devel: 5.16.3

**Comment by sashachoi** [comment]
Can you please share how you solved the problem?
