### ISSUE TITLE
Failed to `add sync` due to read only account in source DB.

### ISSUE THREAD

**Issue by Magicloud** [bucardo/bucardo#244]
Bucardo 5.6.0. Error message:
```
$ bucardo add sync migrate relgroup=mr dbs=source:source,target:target --verbose --debug
SQL: INSERT INTO bucardo.sync (herd,dbs,name) VALUES (?,?,?)
$VAR1 = 'mr';
$VAR2 = 'migrate';
$VAR3 = 'migrate';
WARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=messaging;host=source.rds.amazonaws.com;port=5432 at line 283.
Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::db do failed: ERROR:  permission denied for database source at line 284. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at /usr/local/bin/bucardo line 4670.
```

Seems unexpected. Line 4670 is inserting `bucardo.sync`. Why does it connect to my source DB? I got this because I use a read only role for Bucardo in case I misoperated. The bucardo DB running locally works fine and adding dbs/tables all worked.

**Comment by kritik** [comment]
Have the same issue on the same version. Added some debugging.
```perl
chop $qs;
    $dbh = DBI->connect($DSN, $bcargs->{dbuser}, $bcargs->{dbpass}, {AutoCommit=>0,RaiseError=>1,PrintError=>0});
    print "DSN2: $DSN\n";
    $dbh->do(qq{select count(*) from bucardo.sync}); # is running on bucardo server
    $SQL = "INSERT INTO bucardo.sync ($columns) VALUES ($qs)";
    $DEBUG and warn "SQL: $SQL\n";
    $sth = $dbh->prepare($SQL);
    print "dbh $dbh\n";
    print "sth $sth\n";
    $DEBUG and warn Dumper values %$dbcols;
    eval {
            print "before"; # printed
        $count = $sth->execute(values %$dbcols); # is running on master server
        print "after";
    };
```

I also tried both ubuntu deb and compiled from source versions

**Comment by Magicloud** [comment]
@kritik I had to use a writable account to make this work. And found out that, although the error says "insert to sync", actually, it breaks on creating some triggers in source DB. When using read-only account, surely the triggers are failed to create.

**Comment by kritik** [comment]
interesting.... I'm using in the source DB (also AWS RDS) user which was created during DB in creation. It seems that this user has to have maximum available rights :)
