### ISSUE TITLE
Why does bucardo requires plperlu ?

### ISSUE THREAD

**Issue by 131** [bucardo/bucardo#248]
I understand that `plperlu` is an unsafe version of `plperl`.
In managed environments, it will be hard to find a provider with this extension available (when `plperl` is always available)

Whould bucardo be compliant with a simple `plperl` ? 
If not, can you explain us why ?

**Comment by turnstep** [comment]
The plperlu functions need to (among other things) connect to databases via DBI, so the locked down version of plperl will not work. However, the long-term plan is to remove the plperl and plperlu dependencies entirely, and rely more on the `bucardo` program to do all the things the current functions do.
