### ISSUE TITLE
SSL error :unknown protocol

### ISSUE THREAD

**Issue by bsach280** [bucardo/bucardo#252]
when i run cmd for add all tables its gives me following error ,,
bucardo add all tables --herd=two_one db=<dbname>
DBI connect('dbname=epramaan_db;host=<ip> ;port=7531','sachin',...) failed: SSL error: unknown protocol
This may indicate that the server does not support any SSL protocol version between TLSv1.2 and TLSv1.2.
expected authentication request from server, but received S at /usr/local/bin/bucardo line 8683.
how to resolve it

**Comment by jonjensen** [comment]
It appears you need to set up your Postgres server to allow TLSv1.2! Sorry, configuring the basic Postgres connections is beyond the scope of Bucardo.
