### ISSUE TITLE
Bucardo just keeps on adding data, but I can't find single row in target DB

### ISSUE THREAD

**Issue by venomwaqar** [bucardo/bucardo#259]
I've successfully configured a bucardo replication for PSQL DBs. From the looks of pg_activity_table, seems like it is doing COPY in both source and target database. `bucardo status sync_name` showing it is still running, when I ran `SELECT pg_size_pretty(pg_database_size(current_database()));` in target DB, it shows I've GBs of data, but I can't seem to find single row in any of the table?

Does bucardo commits the rows after traversing the complete database? or one table at a time?
<img width="511" alt="Screenshot 2023-11-06 at 3 19 51 AM" src="https://github.com/bucardo/bucardo/assets/26359286/12a3fcb5-ba9d-419e-b6a4-83048435a848">

**Comment by wajahat-eurus** [comment]
I am also having the same issue, Can anybody shed some light?

**Comment by jonjensen** [comment]
Bucardo commits in one transaction all the changes in a single sync run. So if you have a ton of changes, yes, it'll do a lot before it commits.
