### ISSUE TITLE
Add Two-Phase Commit Support

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#30]
Add an option to use two-phase commit to support synchronous replication. [Discussion here](https://mail.endcrypt.com/pipermail/bucardo-general/2012-October/001628.html), and continuing [here](https://mail.endcrypt.com/pipermail/bucardo-general/2012-November/001633.html).

**Comment by jonjensen** [comment]
Great idea, but closing after more than a decade of nobody stepping up with code for this.
