### ISSUE TITLE
onetime Does Not Work in 4.99.6

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#37]
Tried to set up a two master configuration where one master already had data and the other didn't. Hit `reload config` and the daemons fired up, which is great, but nothing was copied. I changed a row in the populated master, and the updated data was copied to the other, but none of the existing data was. The `onetime` attribute was set to 0 after that.

Probably something simple…

**Comment by jonjensen** [comment]
@turnstep You were apparently working on this. It's 8 years old now, so I imagine it either got fixed or is no longer needed. Can you advise?

**Comment by turnstep** [comment]
Agree that we might as well close it now,
