### ISSUE TITLE
Not replicating, cryptic error(?) message

### ISSUE THREAD

**Issue by MikeEmery** [bucardo/bucardo#38]
I'm using 4.99.6.  I have two databases set up for replication and everything seems ok.  When I run the replication I don't see any rows moving accross and I see this repeatedly in the bucardo log:

(2767) [Thu Jan 31 01:10:36 2013] KID Kid 2767 exiting at cleanup_kid. Sync "db_production" public.delayed_jobs Reason: Bucardo=HASH(0x112b3e8) Line: 2632

Is this actually an error?  If so how do I find out what's causing it?

**Comment by turnstep** [comment]
Closing: no response in many years
