### ISSUE TITLE
Bucardo_ctl reports date in the future for 'Last good time'

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#48]
ID: 56
Component: bucardo_ctl
Version: 4.4.0
Date: 2010-11-29 10:09 EST
Author: geoff (gjsw@utas.edu.au)

---

Hi,

Bucardo_ctl is reporting dates in the future for the 'last good time' field
when I do a bucardo_ctl status syncname.  The server I'm running this on is
based in Tasmania, Australia where the current timezone offset is currently
UTC/GMT +11 hours.
#### Steps to reproduce:

Just run bucardo_ctl status syncname when your system timezone is set to
Australia/Hobart.  This is on a centos 5.5 64 bit box.
#### Expected behaviour:

Last good time should be in the past
#### Actual behaviour:

bucardo_ctl status syncname is currently reporting:

Last good time:       Nov 30, 2010 04:09:55 
(and Last bad time:        Nov 30, 2010 04:09:29)

But the system date command reports the current date as:

`Mon Nov 29 20:53:30 EST 2010`

And psql reports the correct time:

```
bucardo=# select to_char(current_timestamp, 'YYYY-mm-dd HH24:MI:SS TZ');
         to_char
 2010-11-29 21:07:46 EST
(1 row)
```
#### Environment

OS:
Centos 5.5 i86_64

Packages:
bucardo-4.4.0-2.el5
perl-DBIx-Safe-1.2.5-6.el5
perl-version-0.7203-1.el5
nagios-plugins-perl-1.4.15-2.el5
perl-5.8.8-32.el5_5.2
perl-DBD-Pg-2.17.1-1.el5.rf
perl-DBI-1.52-2.el5
compat-postgresql-libs-4-1PGDG.rhel5
postgresql-libs-8.4.5-1PGDG.rhel5
postgresql-devel-8.4.5-1PGDG.rhel5
postgresql-libs-8.1.21-1.el5_5.1
postgis-1.3.6-1.rhel5
postgresql-8.4.5-1PGDG.rhel5
postgresql-contrib-8.4.5-1PGDG.rhel5
postgresql-server-8.4.5-1PGDG.rhel5
postgresql-plperl-8.4.5-1PGDG.rhel5

**Comment by jonjensen** [comment]
This report is 10 years old and predates Bucardo 5. I tried anyway to reproduce it and found it works fine for me. I started in MST7MDT, then switched the system to Australia/Hobart and restarted Postgres & Bucardo, and `bucardo status` shows Australia local times.
