### ISSUE TITLE
[Version 4.4.8] Column with name "tablename"

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#50]
ID: 105
Component: bucardo_ctl
Version: 4.4.8
Date: 2012-06-27 10:38 EDT
Author: Hermann D. Schimpf (hschimpf@hds-solutions.net)

---

Hi,
I'm using Bucardo from 2 years ago. I want to congratulate for this tool, it
helped me very much.

Ok, I tell you my problem. I found a bug using Bucardo. If I have a table with
a column named "tablename", it conflicts with a internal variable from Bucardo
process (I guess) and I can't replicate this table with Bucardo. I don't know
Perl very much, I'm Java programmer. So I can't found exactly the location of
this problem on Bucardo sources.

I'll be very grateful to the fix of this bug, because I have 5 servers in
master-master replication and I need replicate that table.

Thanx

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
