### ISSUE TITLE
DBD::Pg::st execute failed

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#51]
ID: 109
Component: bucardo_ctl
Version: HEAD
Date: 2012-08-01 04:18 EDT
Author: Yang Hua Jie (yhjhoo@163.com)

---

when I tried to use the command bucardo_ctl to add the sequences to be
synchronize, I encounter the following error.

$sudo bucardo_ctl add all sequences db=db1
DBD::Pg::st execute failed: ERROR:  new row for relation "goat" violates check
constraint "standard_conflict_sequence" at /usr/bin/bucardo_ctl line 3670.

**Comment by jonjensen** [comment]
This predates Bucardo 5 and is unlikely to be relevant now. Closing.
