### ISSUE TITLE
Better installation suggestions

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#58]
ID: 83
Component: Installation
Version: unspecified
Date: 2011-08-01 15:11 EDT
Author: Greg Sabino Mullane (greg@endpoint.com)

---

Would be nice if the INSTALL file and/or the installer made an effort to find
and point out missing prerequisites, including how to install on common
platforms (e.g. sudo yum install perl-DBIx-Safe)

**Comment by jonjensen** [comment]
It would be nice; patches accepted.
