### ISSUE TITLE
Installation reports pl/perlu not installed

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#60]
ID: 1
Component: Installation
Version: 4.4.0
Date: 2009-11-17 03:58 EST
Author: Greg Sabino Mullane (greg@endpoint.com)

---

Although bucardo_ctl install claims pl/perlu is not installed and working, it is.

**Comment by jonjensen** [comment]
Specific details are lacking here, and this is 11 years old, and I haven't heard recent similar reports, so closing.
