### ISSUE TITLE
Documentation on custom conflict resolution

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#61]
ID: 30
Component: Wiki
Version: HEAD
Date: 2010-01-13 14:40 EST
Author: Greg Sabino Mullane (greg@endpoint.com)

---

The wiki needs a good explanation and examples of custom conflict resolution
code. Should probably have some in the tests as well (so perhaps write both at
the same time).

**Comment by jonjensen** [comment]
Not enough round tuits, apparently.
