### ISSUE TITLE
"bucardo_ctl install" failing on debian / lack of documentation

### ISSUE THREAD

**Issue by phinjensen** [bucardo/bucardo#62]
ID: 101
Component: Wiki
Version: 4.4.0
Date: 2012-03-29 15:21 EDT
Author: Chris Recktenwald (bucardo-contact@citecs.de)

---

installation on debian 6.0 from debian packet bucardo 4.4.0-1

doc used: http://bucardo.org/wiki/Bucardo/Installation
(which is kind of "but first" structured)

the way to do this - without fiddling around the authentication scheme for the
"postgres" user in /etc/postgresql/9.1/main/pg_hba.conf

as system user root:

```
# set up directory
mkdir /var/run/bucardo
chown bucardo:bucardo /var/run/bucardo

# pre-install requirements
su - postgres -c psql
create user bucardo with password 'goat' superuser; -- hardcoded in
bucardo_ctl, which is a stupid[tm] idea
create database bucardo owner bucardo;
\c bucardo bucardo
\dL
create language plperl;
create language plperlu;
\dL
\q

# what was intended tu run out of the box
bucardo_ctl install
3
bucardo
4
bucardo
goat
goat


# set a new passwort
su - postgres -c psql
\password bucardo bucardo
  secret
  secret
\q

# be sure do execute this on any of your database servers
```

**Comment by jonjensen** [comment]
This predates Bucardo 5 and we haven't heard recent reports, so closing.
