### ISSUE TITLE
Add Custom Background Worker Support

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#69]
PostgreSQL 9.3 adds support for [custom background workers](https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.3#Custom_Background_Workers). It would be cool to have this for Bucardo, so that when Postgres starts, so does Bucardo, and when Postgres shuts down, so does Bucardo. Would need to be sure that Bucardo could be restarted without restarting Postgres, though.

**Comment by jonjensen** [comment]
Agreed that this would be cool, but in nearly 10 years nobody has stepped up to give it a shot, so closing.
