### ISSUE TITLE
Undefined database handle in `add all tables`

### ISSUE THREAD

**Issue by zundra** [bucardo/bucardo#7]
Hi

I get the following error when trying to use the bucardo_ctl commadn to add tables:

```
ubuntu@ip-10-171-65-39:~/Bucardo-4.5.0$ bucardo_ctl add all tables db=production
Can't call method "prepare" on an undefined value at /home/ubuntu/perl5/bin/bucardo_ctl line 3622.
```

This happens if I install from source or use the debian package via apt-get

**Comment by jonjensen** [comment]
Can't reproduce on current Bucardo.
