### ISSUE TITLE
Validate Command is not Comprehensive

### ISSUE THREAD

**Issue by theory** [bucardo/bucardo#70]
The `bucardo validate` command does some basic sync validation by calling the `validate_sync()` function in the database. However, when a sync is activated, Buardo.pm code does _a whole lot more_ to validate a sync. This is good, to make sure a sync is valid on startup. But not very useful to the user, who will not know a sync is invalid until they notice it not working and dig through the Bucardo log looking for reasons -- even though `bucardo validate` shows the sync is fine.

I think that sync validation should be sync validation, and no matter what code is validating should do its damnedest to do so. Even if the MCP is not running.

So this is a a todo (and followup to #65) requesting that sync validation be encapsulated in one place, and runnable by the client _or_ the MCP. In both cases, the caller should be able to get a complete list of issues to display (client) or log (MCP).

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
