### ISSUE TITLE
Bucardo failed wih syntax error a or near ")"

### ISSUE THREAD

**Issue by miadavidson** [bucardo/bucardo#72]
Hi Dave..

I am new to Bucardo. I downloaded the Bucardo 5 and getting error on the sync module

ARNING:  Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=bxtrans;host=xxx.xxx.xxx adcl.net at line 1010.
CONTEXT:  PL/Perl function "validate_sync"
SQL statement "SELECT validate_sync('bxsync')"
PL/Perl function "validate_sync"
Failed to add sync: DBD::Pg::st execute failed: ERROR:  DBD::Pg::st execute failed: ERROR:  syntax error at or near ")"
LINE 7:             WHERE    attrelid IN () AND attnum > 0 AND NOT a...
                                                           ^ at line 1010. at line 30.
CONTEXT:  PL/Perl function "validate_sync" at /usr/local/bin/bucardo line 4000.

**Comment by itJunky** [comment]
I have a same error =(

**Comment by jonjensen** [comment]
This was fixed in this commit:

```
commit e6529b1ee02c729a389eff3b306154be7e4c0f74
Author: Greg Sabino Mullane <greg@endpoint.com>
Date:   Tue Dec 3 12:10:55 2013 -0500

    Check @tableoids, not tablelist, as the latter may be empty (inside validate_sync)
```
