### ISSUE TITLE
dist/bucardo-logfiles.patch outdated

### ISSUE THREAD

**Issue by dgoo2308** [bucardo/bucardo#73]
dist/bucardo-logfiles.patch does not work when building latest master.

@@ -135,9 +135,9 @@ log_showpid|1|Show PID in the log output?
should be:
@@ -139,9 +139,9 @@ log_showpid|1|Show PID in the log output?

and for:

@@ -161,7 +161,7 @@ email_debug_file||File to save a copy of all outgoing emails to
flatfile_dir|.|Directory to store the flatfile output inside of
host_safety_check||Regex to make sure we don't accidentally run where we should not
isolation_level|repeatable read|Default isolation level: can be serializable or repeatable read
piddir|/var/run/bucardo|Directory holding Bucardo PID files
- ...
  +....

should be:

@@ -161,7 +161,7 @@ email_debug_file||File to save a copy of all outgoing emails to
flatfile_dir|.|Directory to store the flatfile output inside of
flatfile_dir|.|Directory to store the flatfile output inside of
host_safety_check||Regex to make sure we don't accidentally run where we should not
isolation_level|repeatable read|Default isolation level: can be serializable or repeatable read
piddir|/var/run/bucardo|Directory holding Bucardo PID files
quick_delta_check|1|Whether to do a quick scan of delta activity
-....
+.....

**Comment by jonjensen** [comment]
Updated in commit 2299fef7dc0a96c8572. Closing.
