### ISSUE TITLE
Sync will stop when 1 server is down.

### ISSUE THREAD

**Issue by bruno911** [bucardo/bucardo#74]
Hi All,
First I would like to congratulate every contributor as bucardo 4.99.11 is working really well. 
I notice, well maybe is a known issue, that if 1 server is down everything will stop without error messages. Consider this scenario:

db1<=>db2<=>db3
bucardo add db db1
bucardo add db db2
bucardo add db db3

bucardo add table tbl_test herd=therd

bucardo add dbgroup tgroup db1:source db2:source db3:source

bucardo add sync foobar relgroup=therd dbs=tgroup

Then if I switch off db3, the sync between db1<=>db2 will also stop.

Even if I create 2 different syncs:
db1<=>db2
db1<=>db3

if one is off everything will stop. The work around I found for that is to create a node js script that will connect the servers and when one server goes down it will create all the syncs again excluding the server that is down, and then when that server come up, node js will run the commands to add a sync will all the databases, the problem with this is that most of the time some rows are missing.

Best regards,
Bruno Quintana.

**Comment by umttt** [comment]
Hi. The problem still occurs in version 5.0.0. Is this solved in version 5.3.0 ?

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
