### ISSUE TITLE
bucardo install ignores --dbuser and --dbname options

### ISSUE THREAD

**Issue by eggyknap** [bucardo/bucardo#75]
[josh@eddie ~/devel/bucardo]$ ./bucardo install --pid-dir /home/josh/devel/bucardo/pid/ --dbport 3287 --dbname bucardo --dbuser josh
This will install the bucardo database into an existing Postgres cluster.
Postgres must have been compiled with Perl support,
and you must connect as a superuser

Current connection settings:
1. Host:           <none>
2. Port:           3287
3. User:           postgres
4. Database:       postgres
5. PID directory:  /home/josh/devel/bucardo/pid/

**Comment by joshuabaird** [comment]
This has regressed in 5.4.1.

**Comment by machack666** [comment]
Thanks for the report; fixed in a71482ad.
