### ISSUE TITLE
bucardo start should have an option to check the pidfile to see that it points to a real process

### ISSUE THREAD

**Issue by eggyknap** [bucardo/bucardo#80]
If the MCP is forcefully killed, "bucardo start" reports that it's already running, and the pid file must be removed manually before it will start again. It would be nice to have a --force option or some such on the start command to check that the pid file corresponds to a real process, or perhaps even to ping the daemon, and if it fails, try to find and kill the MCP process (without killing any other MCP running on the box, I guess) and remove the pid file, before trying to start.

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
