### ISSUE TITLE
Conflict resolution customcode seems to be broken

### ISSUE THREAD

**Issue by joshwilliams** [bucardo/bucardo#81]
When writing a custom conflict resolver...

bucardo add customcode myconflicthandler whenrun=conflict sync=mysync src_code=conflict.pl
bucardo update sync mysync conflict_strategy='bucardo_custom'

... something resembling the following appears in the logs:

KID (mysync) Kid 6201 exiting at cleanup_kid. Sync "mysync" public.t1 Reason: Not a HASH reference at /usr/local/share/perl/5.14.2/Bucardo.pm line 3569. Line: 4881

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
