### ISSUE TITLE
Using bucardo remote database without superuser access

### ISSUE THREAD

**Issue by ocZio** [bucardo/bucardo#83]
Hello,

I am using Bucardo in MASTER/MASTER mode and I was wondering if there is a possibility to restrict the access to the remote MASTER database to not have superuser access.

Here is what I tried:
- created a database and gave full permission to a sync user
- added the sync with bucardo (the database/table and sync), this works fine
  Once I started the bucardo the following error appears in the logs:

``` bash
(31081) [Thu May  1 14:39:45 2014] KID (mysync) Kid has died, error is: DBD::Pg::db do failed: ERROR:  permission denied to set parameter "session_replication_role" at /usr/local/share/perl/5.14.2/Bucardo.pm line 2731.
Line: 2778
Main DB state: ? Error: none
DB localmachine state: ? Error: none
DB remotemachine state: 42501 Error: 7
```

Is there an alternative or any way I can limit the remote access to NOT HAVE superuser access? This is a real security issue in my case.

Thanks!

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.

**Comment by ocZio** [comment]
Thank you for the quick response. Appreciated.
