### ISSUE TITLE
Feature request: Ability to roll bucardo logs

### ISSUE THREAD

**Issue by anastrophe** [bucardo/bucardo#84]
Manually rolling the bucardo logs ('mv log.bucardo log.bucardo.0') then issuing a 'bucardo reload config', will generate a new log.bucardo file, however, the mv'ed file will continue to accumulate data, until you manually issue a 'bucardo stop' then 'bucardo start'.

It would be nice if the logs could be cleanly rolled without having to issue a full stop/start cycle.

This is only really relevant when log_level is set high, such as 'debug'. Under 'terse' logging the logs remain within the kilobyte range for the most part - rather than the gigabyte range as debug does on a busy server.

**Comment by turnstep** [comment]
Please try out the "bucardo reopen" command; it should do what you need.
