### ISSUE TITLE
Status does not feel if the slave is down

### ISSUE THREAD

**Issue by RajanVillalobos** [bucardo/bucardo#87]
I am using bucardo as third party to postgresql replication between two sites. everything ok except buacrdo status <sync_name>. I have a Master-slave sync on master server. when I poweroff the slave server and call buacrdo status <sync_name> on master sell Active

Last good                : Aug 04, 2014 03:55:02 (time to run: 1s)
Rows deleted/inserted    : 0 / 1
Sync name                : dodo
Current state            : Good
Source relgroup/database : dodo / master_erp3_192_168_0_183
Tables in sync           : 2
Status                   : Active
Check time               : None
Overdue time             : 00:00:00
Expired time             : 00:00:00
Stayalive/Kidsalive      : Yes / Yes
Rebuild index            : No
Autokick                 : Yes
Onetimecopy              : No
Post-copy analyze        : Yes
Last error:              : 
I that normal ? where should I find the real status ?

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
