### ISSUE TITLE
Downloads link in INSTALL

### ISSUE THREAD

**Issue by Paxa** [bucardo/bucardo#91]
Here https://github.com/bucardo/bucardo/blob/master/INSTALL
link to http://bucardo.org/wiki/Bucardo/downloads is broken

**Comment by Paxa** [comment]
This also looks outdated https://bucardo.org/wiki/Bucardo/Installation

* bucardo instead of bucardo_ctl
* `bucardo_ctl add database <dbname>` should be `bucardo add db <<dbname> dbname=<dbname>`

**Comment by turnstep** [comment]
Thanks, I put a better link in the INSTALL and will update that wiki page at some point. :)
