### ISSUE TITLE
Foreign key restriction not work on target db

### ISSUE THREAD

**Issue by voltmodder** [bucardo/bucardo#93]
Hi!
I have 2 Postgresql databases on 2 servers both Postgresql has version 9.3.5,
both servers on debian 7. Bucardo version 5.3.1 installed on same server as
source db - db1.

On server 1 I have a db1 (source) with schema "core" and table "client".
structure of table client is
CREATE TABLE core.client
(
  client_id bigint NOT NULL,
  client_type_id smallint NOT NULL,
  client_last_name character varying(100),
  client_first_name character varying(100),
  client_create_dt timestamp with time zone NOT NULL,
  client_delete_dt timestamp with time zone,
  CONSTRAINT pk_client PRIMARY KEY (client_id)
);
and it has a foreign key to table client_type: constraint "fk_client$type"
foreign key (client_type_id) references core.client_type (client_type_id).

On server 2 I have a db2 (target) with schema "corewh" and table "client"
structure of this table is little different.
CREATE TABLE corewh.client
(
  client_id bigint NOT NULL,
  client_type_id smallint NOT NULL,
  client_last_name character varying(100),
  client_first_name character varying(100),
  client_organization_id bigint NOT NULL,
  client_create_dt timestamp with time zone NOT NULL,
  client_delete_dt timestamp with time zone,
  CONSTRAINT pk_client PRIMARY KEY (client_id)
);
and is has the same foreign key to table client_type: constraint
"fk_client$type" foreign key (client_type_id) references corewh.client_type
(client_type_id).

i use this command to add table client to sync (dbgroup with db1 and db2,
relgroup=sync1 and sync=sync1 already added).

bucardo add table core.client db=db1 relgroup=sync1
bucardo add customname core.client corewh.client db=db2
bucardo add customcols core.client "select client_id, client_type_id,
client_last_name, client_first_name,  (select organization_id from
core.organization) AS client_organization_id, client_create_dt,
client_delete_dt" db=db2

And i had sutiation that on db2 table client_type is empty but records from
table client successfully replicated from db1 to db2. When i try manually
insert record to table client on db2 and i have foreign key error but bucardo
somehow manage to insert rows from db1 ignoring fireign key restrictions.

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
