### ISSUE TITLE
"Exiting eval via redo at /usr/local/share/perl/5.10.1/Bucardo.pm line 1465."

### ISSUE THREAD

**Issue by anastrophe** [bucardo/bucardo#94]
After an indeterminate uptime, my bucardo logs begin filling with this line, iterated (very approximately) about 3 times per second. Restarting bucardo will clear it for a while, but eventually it kicks in again.

bucardo v 5.3.1
debian squeeze 32bit
postgresql 9.1

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
