### ISSUE TITLE
Bug. Mysql set transaction level

### ISSUE THREAD

**Issue by arturgspb** [bucardo/bucardo#98]
Replacation Master Pg -> Slave MySql 

"SET TRANSACTION READ WRITE ISOLATION LEVEL SERIALIZABLE"
https://github.com/bucardo/bucardo/blob/master/Bucardo.pm#L5164
This code do error with mysql 5.6.

Logs:
(23436) [Wed Jul 15 12:55:05 2015] KID (mysql_sync_delta) Warning! Aborting due to exception for public.employess:? Error was DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQ
(23436) [Wed Jul 15 12:55:05 2015] KID (mysql_sync_delta) Kid has died, error is: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use
(23436) [Wed Jul 15 12:55:05 2015] KID (mysql_sync_delta) Kid 23436 exiting at cleanup_kid. Sync "mysql_sync_delta" public.employess Reason: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that correspon

**Comment by turnstep** [comment]
Thanks, fixed in 358ebf836762efaa3220abcd13807fbbf9a20514

**Comment by arturgspb** [comment]
Thank you!
