### ISSUE TITLE
Need to recreate /var/run/bucardo after reboot before bucardo start

### ISSUE THREAD

**Issue by FredyKonig** [bucardo/bucardo#99]
The **bucardo start** command complains about the folder /var/run/bucardo

> $ bucardo start
> Checking for existing processes
> Could not create "/var/run/bucardo/fullstopbucardo": No such file or directory

The solution is to create the folder before the first "bucardo start" 
 after a reboot the folder is not here any more.

It would be good to include the creation of this folder inside the bucardo command (if the folder does not exists)

Thanks

**Comment by FredyKonig** [comment]
An solution:


nano /usr/local/bin/bucardo

...
sub start {

    ## Attempt to start the Bucardo daemon
    ## Arguments: none
    ## Returns: undef

    ## Write a note to the 'reason' log file
    ## This will automatically write any nouns in as well
    append_reason_file('start');
    print "Create pid directory: - $PIDDIR  - before start ";
    my $ouput_mkdir = `mkdir -p  $PIDDIR`;
    ## Refuse to go on if we get a ping response within 5 seconds
    $QUIET or print "Checking for existing processes\n";
...

**Comment by gustavovalverde** [comment]
¿No updates on this? cc: @turnstep

**Comment by FredyKonig** [comment]
Hi gustavovalverde ,
there are 2 PR for it
https://github.com/bucardo/bucardo/pull/113 and https://github.com/bucardo/bucardo/pull/100
I recommend the 113 
To the bucardo team please merge 113 and close 100, please.

Thanks

**Comment by FredyKonig** [comment]
thanks machack666
https://github.com/bucardo/bucardo/commits/master/dist/bucardo.init?author=machack666
